#' calFst
#' @description Nei's distance of CCF for each sample-pair
#' @references Lee JK, Wang J, Sa JK, et al. Spatiotemporal genomic architecture informs precision oncology in glioblastoma. 
#' Nat Genet. 2017;49(4):594–599. doi:10.1038/ng.3806
#' 
#' @param maf an Maf object generated by readMaf function
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param min.vaf specify the minimum VAF, default is 0.08
#' @param max.vaf specify the minimum VAF, default is 1
#' @param plot logical (Default:TRUE). Whether to show the plot, default TRUE
#' @param use.circle logical (Default:TRUE). Whether to use "circle" as visualization method of correlation matrix
#' default TURE
#' @param title the title of the plot, default is "Nei's distance"
#' 
#' @return Nei's genetic distance matrix and heatmap of sample-pairs from the same patient
#'
#' @examples
#' calNeiDist(maf)
#' @export calNeiDist

nei_dist <- function(df, withinType = FALSE) {
    
    patient <- unique(df$Patient_ID)

    if(withinType){
        type <- unique(df$Tumor_Type)
        if(length(unique(df$Tumor_Sample_Barcode)) < 2){
            message(paste0("Warnings: Only one sample was found of ", type,
                           " in ", patient, ". It you want to compare CCF between regions, withinType should be set as FALSE\n"))
            return(NA)
        }
        
    }
    
    if(length(unique(df$Tumor_Sample_Barcode)) < 2){
        message(paste0("Warnings: Only one sample was found of ",patient,"."))
        return(NA)
    }
    
    df <- tidyr::pivot_wider(df,
                             names_from = Tumor_Sample_Barcode,
                             values_from = CCF,
                             values_fill = list(CCF = 0)
    ) %>%
        dplyr::select(-Patient_ID, -mutation_id, -Tumor_Type)
    
    dist <- diag(0, nrow = ncol(df), ncol = ncol(df))
    
    for (i in 1:(ncol(df) - 1)) {
        for (j in (i + 1):ncol(df)) {
            x <- as.vector(df[, i])
            y <- as.vector(df[, j])
            
            x_ <- sum(x ^ 2 + (1 - x) ^ 2)
            y_ <- sum(y ^ 2 + (1 - y) ^ 2)
            
            xy <- sum(x * y + (1 - x) * (1 - y))
            
            dist[i, j] <- dist[j, i] <- -log(xy / sqrt(x_ * y_))
        }
    }
    rownames(dist) <- colnames(df)
    colnames(dist) <- colnames(df)
    return(dist)

}

groupByTypeND <- function(df){
    
    types <- unique(df$Tumor_Type)
    
    Nei.dist  <- df %>% 
        dplyr::group_by(Tumor_Type) %>% 
        dplyr::group_map(~nei_dist(., withinType = TRUE), keep = TRUE) %>% 
        rlang::set_names(types)
    
    Nei.dist <- Nei.dist[!is.na(Nei.dist)]
    
}

calNeiDist <- function(maf, 
    patient.id = NULL, 
    min.vaf = 0.08,
    max.vaf = 1,
    plot = TRUE, 
    use.circle = TRUE, 
    title = NULL,
    withinType = FALSE) {
    
    mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Calculation of Nei’s distance requires CCF data." ,
            "No CCF data was found when generate Maf object with readMaf function"))
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
    }

    
    if(withinType){
        if(!"Clonal_Status" %in% colnames(mafData)){
            stop("Clonal_Status of mutations should be contained in MAF when withinType is TRUE") 
        }
        mafData <- mafData %>% 
            dplyr::filter(Clonal_Status == "Subclonal")
    }
    Nei.dist <- mafData %>%
        dplyr::filter(Patient_ID %in% patient.id) %>%
        tidyr::unite(
            "mutation_id",
            c(
                "Chromosome",
                "Start_Position",
                "Reference_Allele",
                "Tumor_Seq_Allele2"
            ),
            sep = ":",
            remove = FALSE
        ) %>%
        dplyr::mutate(
            CCF = dplyr::if_else(is.na(CCF), 0, CCF)
        ) %>% 
        dplyr::filter(VAF_adj > min.vaf & VAF_adj < max.vaf)%>% 
        dplyr::select(
                mutation_id,
                Tumor_Type,
                Tumor_Sample_Barcode,
                Patient_ID,
                CCF) %>%
            data.table::as.data.table()
    ## fresh patient id
    patient.id <- unique(Nei.dist$Patient_ID)
    Nei.plot <- list()
    Nei.avg <- list()
    avg.list <- c()
    if(withinType){
        Nei.dist <- Nei.dist %>% 
            dplyr::group_by(Patient_ID) %>%
            dplyr::group_map(~groupByTypeND(.), keep = TRUE) %>%
            rlang::set_names(patient.id)
        
        dist.list <- list()
        type.list <- c()
        patient.list <- c()
        for(patient in names(Nei.dist)){
            
            ## get result for each patient
            Nei.dist.p <- Nei.dist[[patient]]
            
            for(type in names(Nei.dist.p)){
                ## get result for each patient in each type
                Nei.dist.p.t <- Nei.dist.p[[type]]
                
                name <- paste0(patient,"_",type) 
                dist.list[[name]] <- Nei.dist.p.t
                type.list <- c(type.list, type)
                patient.list <- c(patient.list,patient)
                ## get average dist
                avg <- mean(Nei.dist.p.t)
                avg.list <- c(avg.list,avg)
                
                Nei.plot[[name]] <- plotCorr(
                    Nei.dist.p.t, 
                    use.circle = use.circle, 
                    title = if(!is.null(title)) title else{paste0("Nei’s distance of ", type," in patient ", patient,
                                                                  ". Average Nei’s distance is ",round(avg,4))}
                    #paste0(Nei’s distance, " of patient ", patient.id[i])
                )
                
            }
        }
        Nei.dist <- dist.list
        Nei.avg <- data.frame(Patient_ID = patient.list,
                              Tumor_Type = type.list,
                              Nei.dist.avg = avg.list)
        
    }
    else{
        Nei.dist <- Nei.dist %>% 
            dplyr::group_by(Patient_ID) %>%
            dplyr::group_map(~nei_dist(., withinType = withinType), keep = TRUE) %>%
            rlang::set_names(patient.id) 
        
        avg.list <- c()
        for(i in 1:length(Nei.dist)){
            avg <- mean(Nei.dist[[i]])
            avg.list <- append(avg.list,avg)
            Nei.plot[[patient.id[i]]] <- plotCorr(
                Nei.dist[[i]], 
                use.circle = use.circle, 
                title = if(!is.null(title)) title else{paste0("Nei’s distance of patient ", patient.id[i],
                                                              ". Average Nei’s distance is ",round(avg,4))}
                #paste0(Nei’s distance, " of patient ", patient.id[i])
            )
        }
        Nei.avg <- data.frame(Patient_ID = patient.id,
                              Nei.dist.avg = avg.list)
    }
    
   return(list(Nei.dist = Nei.dist, Nei.plot =  Nei.plot, Nei.dist.avg = Nei.avg))           

}
