#' @description Density plot of CCFs in paired samples of the patient
#
#' @param maf maf object generated by readMaf.
#' @param show.density logical. If TRUE, the default, perform density estimation.
#' @export ccfDensity
#' 
#' @return
#' @examples
#' ccfDensity(maf, show.density = T)
#' 

ccfDensity <- function(maf, show.density = TRUE){
  patientID <- maf@patientID
  ccfLoci <- maf@ccf.loci
  samples <- as.character(unique(ccfLoci$sample_id))
  pairs <- combn(length(samples), 2, simplify = FALSE)
  
  p <- list()
  p.name <- c()
  i <- 1
  for (pair in pairs){
    S1 <- samples[pair[1]]
    S2 <- samples[pair[2]]
    ccf <- ccfLoci %>% dplyr::filter(sample_id %in% c(S1, S2)) %>%
      dplyr::select(mutation_id, sample_id, cellular_prevalence) %>% 
      tidyr::spread(key = sample_id, value = cellular_prevalence )

    colnames(ccf) <- c("mutation_id", "sample1", "sample2")  
    p[[i]] <- ggplot2::ggplot(data=ccf, aes(x=sample1, y=sample2)) + geom_point(size = 0.5) + xlab(S1) +ylab(S2) +
     xlim(0,1) + ylim(0,1) +
      theme(legend.text = element_text(size=10, face="bold"))+
      theme(legend.title = element_text(size=11, face="bold")) +
      guides(shape = guide_legend(override.aes = list(size = 0.2))) +
      theme_bw() + coord_fixed() +
      theme(panel.background = element_blank()) +
      theme(panel.background = element_rect(colour = "black", size = 0.4)) +
      labs(x = S1, y = S2) +
      ggtitle(paste("CCF density plot in paired samples:\n ", S1, "-", S2, sep = "")) +
      theme(plot.title = element_text(hjust = 0.5))
    
    if (show.density){
      p[[i]] <- p[[i]] + stat_density_2d(aes(fill = ..level..), geom = 'polygon', n = ) +
        scale_fill_gradient(low="#8491B499", high="#E64B35FF")
    }
    p.name <- c(p.name, paste(S1,"-",S2, sep = ""))
    i =  i+1
  }
  names(p) <- p.name
  return(p)
}
