#' @title ccfDensity
#' @description Density plot of CCFs in paired samples of the patient
#' This function is only available when the Maf object was generated along with CCF data. 
#' @param maf a Maf object generated by readMaf function.
#' @param show.density logical. If TRUE, the default, perform density estimation.
#' 
#' @return
#' @examples
#' ccfDensity(maf, show.density = T)
#' @export

ccfDensity <- function(maf, show.density = TRUE){
  maf.dat <- maf@data
  patientID <- maf@patientID
  samples <- as.character(unique(maf.dat$Tumor_Sample_Barcode))
  ## check if ccf data is provided
  if(! "CCF" %in% colnames(maf.dat)){
    stop("ccfDensity function requires CCF data. No CCF data was found when generate Maf object with readMaf function")
  }

  pairs <- combn(length(samples), 2, simplify = FALSE)  
  p <- list()
  p.name <- c()
  i <- 1
  for (pair in pairs){
    S1 <- samples[pair[1]]
    S2 <- samples[pair[2]]
    ccf.pair <- maf.dat %>% dplyr::filter(Tumor_Sample_Barcode %in% c(S1, S2)) %>%
      tidyr::unite("mutation_id", c("Chromosome", "Start_Position", "Reference_Allele", "Tumor_Seq_Allele2"), sep = ":", remove = FALSE) %>% 
      dplyr::select(Tumor_Sample_Barcode, mutation_id, CCF) %>% 
      tidyr::spread(key = Tumor_Sample_Barcode, value = CCF)

    colnames(ccf.pair) <- c("mutation_id", "sample1", "sample2")    
    p[[i]] <- ggplot2::ggplot(data=ccf.pair, aes(x=sample1, y=sample2)) + geom_point(size = 0.5) + xlab(S1) +ylab(S2) +
     xlim(0,1) + ylim(0,1) +
      theme(legend.text = element_text(size=10, face="bold"))+
      theme(legend.title = element_text(size=11, face="bold")) +
      guides(shape = guide_legend(override.aes = list(size = 0.2))) +
      theme_bw() + coord_fixed() +
      theme(panel.background = element_blank()) +
      theme(panel.background = element_rect(colour = "black", size = 0.4)) +
      labs(x = S1, y = S2) +
      ggtitle(paste("CCF density plot in paired samples:\n ", S1, "-", S2, sep = "")) +
      theme(plot.title = element_text(hjust = 0.5))
    
    if(show.density){
      p[[i]] <- p[[i]] + stat_density_2d(aes(fill = ..level..), geom = 'polygon', n = ) +
      scale_fill_gradient(low="#8491B499", high="#E64B35FF")
    }
    p.name <- c(p.name, paste(S1,"-",S2, sep = ""))
    i =  i+1
  }
  names(p) <- p.name
  return(p)
}
