#--- Check phyloTree or phyloTreeList input

checkPhyloTreeInput <- function(object, patient.id = NULL){
  if(is(object, "phyloTree")){
    phylotree_list <- list(object)
    names(phylotree_list) <- unique(getPhyloTreePatient(object))
    return(phylotree_list) 
  }else if(is(object, "phyloTreeList")){
    if(!is.null(patient.id)){
      patient.setdiff <- setdiff(patient.id, names(object))
      if(length(patient.setdiff) > 0){
        stop(paste0(patient.setdiff, " can not be found in phyloTreeList"))
      }
      object<- object[names(object)  %in% patient.id] 
    }
    return(object)
  }else{
    stop("Input should be phyloTree or phyloTreeList object generated by function getPhyloTree!")
  }
}


#--- Check Maf or MafList input


checkMafInput <- function(object,patient.id = NULL){
  if(is(object, "Maf")){
    maf_list <- list(object)
    names(maf_list) <- unique(getMafData(object)$Patient_ID)
    return(maf_list)
  }else if(is(object, "MafList")){
    ## patient filter
    if(!is.null(patient.id)){
      patient.setdiff <- setdiff(patient.id, names(object))
      if(length(patient.setdiff) > 0){
        stop(paste0("Error: patient ", patient.setdiff, " can not be found in MafList."))
      }
      object <- object[names(object) %in% patient.id]
    }
    return(object)
  }else{
    stop("Input should be either Maf or MafList object generated by function readMaf.")
  }
}