#' compareJSI
#'
#' @description The Jaccard similarity index (JSI) is applied to distinguish monoclonal versus polyclonal seeding in metastases
#' @references Hu Z, Li Z, Ma Z, Curtis C: Pan-cancer analysis of clonality and the timing of systemic spread in paired primary tumors and metastases. bioRxiv 2019.
#' @param maf a Maf object generated by readMaf function
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param min.vaf specify the minimum VAF, default is 0.08
#' @param plot logical (Default:TRUE). Whether to show the plot, default TRUE
#' @param use.circle logical (Default:TRUE). Whether to use "circle" as visualization method of correlation matrix
#' @param title the title of the plot, default is "Jaccard similarity"
#'
#' @examples
#' compareJSI(maf)
#' @return correlation matrix and heatmap via Jaccard similarity coefficient method
#' @export compareJSI

JSI_dist <- function(df, pairByType){
    
    patientid <- unique(df$Patient_ID) 
    
    # if(pairByType){
    #     types <- unique(df$Tumor_Type)
    #     if(length(types) < 2){
    #         message(paste0("Warnings: Only one tumor type was found of ",patientid,". It you want to compare CCF between regions, pairByType should be set as FALSE"))
    #         return(NA)
    #     }
    #     df <- df %>% 
    #         tidyr::unite("mutation_id2",
    #                      c("mutation_id",
    #                        "Tumor_Type"),
    #             sep = ":",
    #             remove = FALSE
    #         ) %>%
    #         dplyr::distinct(mutation_id2, .keep_all = T) %>% 
    #         dplyr::select(-mutation_id2 ,-Patient_ID,-Tumor_Sample_Barcode) %>%
    #         tidyr::pivot_wider(names_from = Tumor_Type,
    #                              values_from = VAF,
    #                              values_fill = list(VAF = 0)) %>%
    #         dplyr::ungroup() %>%
    #         dplyr::select(-mutation_id) 
    # }else{
    #     
    #     df <- df %>% 
    #         dplyr::select(-Tumor_Type) %>% 
    #         tidyr::pivot_wider(
    #                              names_from = Tumor_Sample_Barcode,
    #                              values_from = c(VAF),
    #                              values_fill = list(VAF = 0)
    #     ) %>%
    #         dplyr::ungroup() %>%
    #         dplyr::select(-mutation_id, -Patient_ID) 
    # }
    
    # Clonal_Status <- df$Clonal_Status
    # df <- subset(df, select=-Clonal_Status)
    
    if(pairByType){
        if(length(unique(df$Tumor_Type))  < 2 ){
            message(paste0("Warnings: Only one tumor type was found of ",patientid, ". It you want to compare CCF between regions, pairByType should be set as FALSE"))
            return(NA)
        }
    }else{
        if(length(unique(df$Tumor_Sample_Barcode))  < 2 ){
            message(paste0("Warnings: Only one sample was found in ", patientid, "."))
            return(NA)
        } 
    }
    
    ## pairwise heterogeneity
    if(pairByType){
        types <- as.character(unique(df$Tumor_Type))
        pairs <- combn(length(types), 2, simplify = FALSE)
        dist <- diag(1, nrow = length(types), ncol = length(types))
        rownames(dist) <- types
        colnames(dist) <- types
    }else{
        samples <- as.character(unique(df$Tumor_Sample_Barcode))
        pairs <- combn(length(samples), 2, simplify = FALSE)
        dist <- diag(1, nrow = length(samples), ncol = length(samples))
        rownames(dist) <- samples
        colnames(dist) <- samples
    }
    
    PC_1.list <- c()
    PC_2.list <- c()
    SS_12.list <- c()
    JSI.df <- data.frame()
    for (pair in pairs){
        
        if(pairByType){
            name <- paste(types[pair[1]],types[pair[2]], sep = "_")
            vaf.pair <- subset(df, Tumor_Type %in% c(types[pair[1]],types[pair[2]])) %>%
                        tidyr::unite("mutation_id2",
                                     c("mutation_id",
                                       "Tumor_Type"),
                            sep = ":",
                            remove = FALSE
                        ) %>%
                        dplyr::distinct(mutation_id2, .keep_all = T) %>%
                dplyr::select(mutation_id, Tumor_Type, Clonal_Status, VAF) %>% 
                tidyr::pivot_wider(
                    names_from = Tumor_Type,       
                    values_from = c(VAF, Clonal_Status),
                    values_fill = c(VAF = 0, Clonal_Status = 'NA')
                ) %>%
                dplyr::ungroup()
            colnames(vaf.pair) <- c("mutation_id", "vaf1", "vaf2", "status1", "status2")
            
            
        }
        else{
            name <- paste(samples[pair[1]],samples[pair[2]], sep = "_")
            
            vaf.pair <- subset(df, Tumor_Sample_Barcode %in% c(samples[pair[1]],samples[pair[2]])) %>%
                dplyr::select(mutation_id, Tumor_Sample_Barcode, Clonal_Status, VAF) %>% 
                tidyr::pivot_wider(
                    names_from = Tumor_Sample_Barcode,       
                    values_from = c(VAF, Clonal_Status),
                    values_fill = c(VAF = 0, Clonal_Status = 'NA')
                ) %>%
                dplyr::ungroup()
            colnames(vaf.pair) <- c("mutation_id", "vaf1", "vaf2", "status1", "status2")
        }
        
        vaf.pair <- vaf.pair %>% 
            dplyr::filter(vaf1 + vaf2 !=0) %>% 
            data.table::setDT()
        

        PC_1 <- nrow(vaf.pair[status1 == "Clonal" & vaf1>0 & vaf2==0])
        PC_1.list <- c(PC_1.list, PC_1)
        PC_2 <- nrow(vaf.pair[status2 == "Clonal" & vaf1==0 & vaf2>0])
        PC_2.list <- c(PC_2.list, PC_2)
        SS_12 = nrow(vaf.pair[status2=="Subclonal" & status1 == "Subclonal" & vaf1>0 & vaf2>0 ])
        SS_12.list <- c(SS_12.list, SS_12)
        
        
        dist[pair[1],pair[2]] <- dist[pair[2],pair[1]] <- SS_12/(PC_1+PC_2+SS_12)
        
        sub <- data.frame(patientid,name, SS_12/(PC_1+PC_2+SS_12))
        JSI.df <- rbind(JSI.df, sub)
    }
    
    multi <- mean(SS_12.list)/(mean(PC_1.list) + mean(PC_2.list) + mean(SS_12.list))
    JSI.multi <- data.frame(Patient_ID = patientid, JSI.multi = multi)
    
    #return(JSI.dist)
    return(list(JSI.multi = JSI.multi, JSI.pair =  dist, JSI.df = JSI.df))
}    

compareJSI <- function(
    maf, 
    patient.id = NULL,
    pairByType = FALSE,
    min.vaf = 0.08,
    plot = TRUE, 
    use.circle = TRUE, 
    title = NULL) {

    mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Error: calculation of Jaccard similarity requires CCF data." ,
            "No CCF data was found when generate Maf object."))
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
        mafData <- mafData[Patient_ID %in% patient.id,]
    }

    JSI.dist <- mafData %>%
        tidyr::unite(
            "mutation_id",
            c(
                "Chromosome",
                "Start_Position",
                "Reference_Allele",
                "Tumor_Seq_Allele2"
            ),
            sep = ":",
            remove = FALSE
        ) %>%
        dplyr::select(
            mutation_id,
            Tumor_Type,
            Tumor_Sample_Barcode,
            Patient_ID,
            Clonal_Status,
            VAF) %>%
        dplyr::filter(VAF > min.vaf) %>% 
        dplyr::group_by(Patient_ID) %>%
        dplyr::group_map(~JSI_dist(., pairByType), keep = TRUE) %>% 
        rlang::set_names(patient.id)
    
    JSI.dist <- JSI.dist[!is.na(JSI.dist)]
    if(length(JSI.dist) == 0){
        return(NA)
    }
    # patient.id <- names(JSI.dist)
    
    JSI.df <-  plyr::rbind.fill(lapply(JSI.dist, function(x) x$JSI.df)) 
    colnames(JSI.df) <- c("Patient_ID","Pair", "JSI")
    
    JSI.multi <-  plyr::rbind.fill(lapply(JSI.dist, function(x) x$JSI.multi)) 
    
    JSI.plot = list()
    if(plot){
        for(i in 1:length(JSI.dist)){
            JSI.plot[[i]] <- plotCorr(
                JSI.dist[[i]]$JSI.pair, 
                use.circle = use.circle,
                title = if(!is.null(title)) title else{paste0("Jaccard similarity of patient ", patient.id[i])}
                )
        }
        names(JSI.plot) <- patient.id
        JSI.out <- list(
            JSI.multi = JSI.multi, 
            JSI.pair = JSI.df,
            JSI.plot = JSI.plot)
        return(JSI.out)
    }

   JSI.out <- list(
    JSI.multi = JSI.multi, 
    JSI.pair = JSI.df
    )

   return(JSI.out)  
   #return(list(JSI.dist = JSI.dist, JSI.plot =  JSI.plot))  

}

