#' compareJSI
#'
#' @description The Jaccard similarity index (JSI) is applied to distinguish monoclonal versus polyclonal seeding in metastases
#' @references Hu Z, Li Z, Ma Z, Curtis C: Pan-cancer analysis of clonality and the timing of systemic spread in paired primary tumors and metastases. bioRxiv 2019.
#' @param maf a Maf object generated by readMaf function
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param min.vaf specify the minimum VAF_adj, default is 0.08
#' @param plot logical (Default:TRUE). Whether to show the plot, default TRUE
#' @param use.circle logical (Default:TRUE). Whether to use "circle" as visualization method of correlation matrix
#' @param title the title of the plot, default is "Jaccard similarity"
#'
#' @examples
#' compareJSI(maf)
#' @return correlation matrix and heatmap via Jaccard similarity coefficient method
#' @export compareJSI

compareJSI <- function(
    maf, 
    patient.id = NULL,
    pairByType = FALSE,
    min.vaf = 0.08,
    plot = TRUE, 
    use.circle = TRUE, 
    title = NULL) {

    mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Error: calculation of Jaccard similarity requires CCF data." ,
            "No CCF data was found when generate Maf object."))
    }
    
    if(min.vaf < 0){
        stop("Error: min.vaf must be greater than 0")
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
        mafData <- mafData[Patient_ID %in% patient.id,]
    }

    JSI.dist <- mafData %>%
        tidyr::unite(
            "mutation_id",
            c(
                "Chromosome",
                "Start_Position",
                "Reference_Allele",
                "Tumor_Seq_Allele2"
            ),
            sep = ":",
            remove = FALSE
        ) %>%
        dplyr::select(
            mutation_id,
            Tumor_Type,
            Tumor_Sample_Barcode,
            Patient_ID,
            Clonal_Status,
            VAF_adj) %>%
        dplyr::filter(VAF_adj > min.vaf) %>% 
        dplyr::group_by(Patient_ID) %>%
        dplyr::group_map(~JSI_dist(., pairByType), keep = TRUE) %>% 
        rlang::set_names(patient.id)
    
    JSI.dist <- JSI.dist[!is.na(JSI.dist)]
    if(length(JSI.dist) == 0){
        return(NA)
    }
    # patient.id <- names(JSI.dist)
    
    JSI.df <-  plyr::rbind.fill(lapply(JSI.dist, function(x) x$JSI.df)) 
    colnames(JSI.df) <- c("Patient_ID","Pair", "JSI")
    
    JSI.multi <-  plyr::rbind.fill(lapply(JSI.dist, function(x) x$JSI.multi)) 
    
    JSI.plot = list()
    patient.id <- names(JSI.dist)
    if(plot){
        for(i in 1:length(JSI.dist)){
            # 
            dist.mat <- JSI.dist[[i]]$JSI.pair
            mat.value <- sort(unique(as.numeric(dist.mat))) 
            if(length(mat.value[mat.value!=0 &mat.value !=1]) == 0){
                message(paste0("Warnings: there is no JSI greater than 0 within sample pairs,can not calculate JSI for ", patient.id[i], "."))
                JSI.plot[[i]] <- NA
                next
            }
            JSI.plot[[i]] <- plotCorr(
                JSI.dist[[i]]$JSI.pair, 
                use.circle = use.circle,
                title = if(!is.null(title)) title else{paste0("Jaccard similarity of patient ", patient.id[i])}
                )
        }
        names(JSI.plot) <- patient.id
        JSI.plot <- JSI.plot[!is.na(JSI.plot)]
        if(length(JSI.plot) == 0){
            JSI.plot <- NA
        }
        
        JSI.out <- list(
            JSI.multi = JSI.multi, 
            JSI.pair = JSI.df,
            JSI.plot = JSI.plot)
        return(JSI.out)
    }

   JSI.out <- list(
    JSI.multi = JSI.multi, 
    JSI.pair = JSI.df
    )

   return(JSI.out)  
   #return(list(JSI.dist = JSI.dist, JSI.plot =  JSI.plot))  

}

