#' @title ccfAUC
#' @description Calculate MATH score and VAF value could be filtered with minvaf and maxvaf.
#' 
#' @param maf a Maf object generated by readMaf.
#' @param tsb Specify Tumor_Sample_Barcodes for single or all samples from maf of the patient. Default: NULL, which means that output all samples' MATH Score.
#' @param minvaf the minimum variant allele frequencies (VAFs) for filtering variants. Default: 0. Option: on the scale of 0 to 1. 
#' @param maxvaf the maximum variant allele frequencies (VAFs) for filtering variants. Default: 0. Option: on the scale of 0 to 1.
#' @return A list containing MATH scores of all/selected samples.
#' 
#' @examples
#' mathScore(maf, tsb=NULL, minvaf=0.02, maxvaf=1)
#' mathScore(maf, tsb=c("SRR3670035"))
#' 
#' @export mathScore


ccfAUC <- function(mutCCF, tsb=NULL){
    ## extract the loci data from maf
    mutCCF.all <- maf@ccf.loci
    df.AUC <- data.frame(matrix(ncol=3, nrow=0), stringsAsFactors = FALSE)
    colnames(df.AUC) <- c("TumorSampleBarcode", "AUC", "Heterogeneity")
    mutCCF.sort.all <- data.frame(matrix(ncol=3, nrow=0), stringsAsFactors = FALSE)
    colnames(mutCCF.sort.all) <- c("TumorSampleBarcode", "ccf", "prop")
    
    ## specify sample.id
    if (is.null(tsb)) {
        tsb <- unique(mutCCF.all$sample_id)
    }
    
    ## calculate AUC
    for (sample.id in tsb) {
        mutCCF <- mutCCF.all[which(mutCCF.all$sample_id == sample.id), ]
        
        ## calculate each sample's AUC value
        mutCCF.sort <- data.frame(ccf=sort(mutCCF$cellular_prevalence), prop=c(1:nrow(mutCCF))/nrow(mutCCF))
        area <- 0
        
        ## TODO: maybe there will be more accurate method using calculus
        for (i in (1:(nrow(mutCCF)-1))){
            mutArea <- (mutCCF.sort[i,2]+mutCCF.sort[i+1,2])*(mutCCF.sort[i+1,1]-mutCCF.sort[i,1])/2
            area <- mutArea + area
        }
        
        ## Heterogeneous or Homogeneous
        if (area > 0.52) {
            Heterogeneity <- "Heterogeneous"
        } else {
            Heterogeneity <- "Homogeneous"
        }
        
        ## generate elements for mutCCF.sort.all and df.AUC
        row.mutCCF.sort <- cbind(TumorSampleBarcode=rep(sample.id, nrow(mutCCF.sort)), mutCCF.sort)
        mutCCF.sort.all <- rbind(mutCCF.sort.all, row.mutCCF.sort)
        row.AUC <- data.frame(TumorSampleBarcode=sample.id, AUC=area, Heterogeneity=Heterogeneity)
        df.AUC <- rbind(df.AUC, row.AUC)
    }
    
    ## visualise the mutCCF.sort.all data
    ggplot(mutCCF.sort.all, aes(x=ccf, y=prop, group=TumorSampleBarcode, color=TumorSampleBarcode))+ 
        theme_bw()+ 
        geom_point(alpha=0.1)+
        geom_line()+
        theme(
            #legend.position='none', 
            title=element_text(size=10), 
            text=element_text(size=10), 
            panel.grid=element_blank(), 
            panel.border=element_blank(), 
            axis.line=element_line(size=0.25),
            axis.text.x = element_text("CCF"),
            axis.text.y=element_text("Proportion")
        )+
        labs(x="CCF", y="Proportion")+
        ggsci::scale_color_npg()+
        ggsci::scale_fill_npg()
        
    ## result 
    output <- list(data.AUC=df.AUC, plot.AUC=pic)
    return(output)
}


需求：
拟合曲线 area的值标注在图的右上角 
AUC同质性判断（阈值为0.052，大于阈值异质性，小于阈值同质性），星号 Heterogeneous(>0.052); Homogeneous

问题：
星号的位置在最后一个点的上方
