#' getMergedCCF
#' @description calculate merged CCF of each sSNV by integrating CCFs of MRS data. 
#' @references Sun R, Hu Z, Sottoriva A, et al. Between-region genetic divergence reflects the mode and tempo of tumor evolution. 
#' Nat Genet. 2017;49(7):1015–1024. doi:10.1038/ng.3891
#' 
#' 
#' @param mafData the data information of the Maf object generated by readMaf function.
#' @return a data.frame of merged CCF of sSNVs.
#'
#' @examples
#' getMergedCCF(maf)
#' @export getMergedCCF


## calculate merged CCF
getMergedCCF <- function(mafData){
	#mafData <- maf@data
	if("CCF" %in% colnames(mafData)){
		maf_totalDepth <- mafData %>% 
			dplyr::filter(Variant_Type == "SNP") %>%
			tidyr::unite("mutation_id", c("Chromosome", "Start_Position", "Reference_Allele", "Tumor_Seq_Allele2"), sep = ":", remove = FALSE) %>%
			dplyr::mutate(totalDepth = Ref_allele_depth + Alt_allele_depth)

		mergedCCF <- c()
		mutID <- unique(maf_totalDepth$mutation_id)	
		for(mut in mutID){
			mutRecord <- dplyr::filter(maf_totalDepth, mutation_id==mut)
			mutRecord[is.na(mutRecord$CCF), "CCF"] = 0
			snv.mergedCCF <- sum(mutRecord$CCF*mutRecord$totalDepth) / sum(mutRecord$totalDepth)
			if(snv.mergedCCF > 1){snv.mergeCCF = 1}
			mergedCCF <- c(mergedCCF, snv.mergedCCF)
		}
		return(data.frame(mutation_id=mutID, mergedCCF=mergedCCF,stringsAsFactors = FALSE))		
	}
	else{
		stop("No ccf data was found in Maf object")
	}
}
