#' @title getPhyloTree
#' 
#' @param maf Maf or MafList object generated by readMaf function
#' @param patient.id Select the specific patients. Default: NULL, all patients are included.
#' @param method Approach to construct phylogenetic trees.Choose one of "NJ"(Neibor-Joining),"MP"(maximum parsimony),"ML"(maximum likelihood),""FASTME.ols" or "FASTME.bal". 
#' @param min.vaf The minimum value of vaf. Default 0.02.
#' @param bootstrap.rep.num Bootstrap iterations.. Default 100.
#' @param ... Other options passed to \code{\link{subsetMaf}}
#' 
#' 
#' @examples
#' maf.File <- system.file("extdata", "HCC6046.maf", package = "MesKit")
#' ccf.File <- system.file("extdata", "HCC6046.CCF.txt", package = "MesKit")
#' maf <- readMaf(mafFile=maf.File, refBuild="hg19")
#' phyloTree <- getPhyloTree(maf)
#' @return  PhyloTree or phyloTreeList object
#' @import phangorn ape
#' @export getPhyloTree

getPhyloTree <- function(maf,
                      patient.id = NULL, 
                      method = "NJ",
                      min.vaf = 0.02, 
                      bootstrap.rep.num = 100,...){
  
  method <- match.arg(method, choices = c("NJ","MP","ML","FASTME.ols","FASTME.bal"), several.ok = FALSE)
  
  ## check input data
  maf_list <- checkMafInput(maf, patient.id = patient.id)
  
  phyloTree_patient_list <- list()
  for(m in maf_list){
      maf_data <- subsetMaf(m,min.vaf = min.vaf)
      
      refBuild <- getMafRef(m)
      patient <- unique(maf_data$Patient_ID)
      
      ## information input
      binary.matrix <- getMutMatrix(maf_data, use.ccf = FALSE)
      if("CCF" %in% colnames(maf_data)){
          ccf.matrix <- getMutMatrix(maf_data, use.ccf = TRUE)
      }else{
          ccf.matrix <- matrix() 
      }
      mut_dat <- t(binary.matrix)
      if(method == "NJ"){
          matTree <- nj(dist.gene(mut_dat))
          bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e)nj(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
      }else if(method == "MP"){
          matTree <- byMP(mut_dat)
          bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e){byMP(e)},B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100 
      }else if(method == "ML"){
          matTree <- byML(mut_dat)
          bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e)byML(e),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
      }else if(method == "FASTME.bal"){
          matTree <- ape::fastme.bal(dist.gene(mut_dat))
          bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e) ape::fastme.bal(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
      }else if(method == "FASTME.ols"){
          matTree <- ape::fastme.ols(dist.gene(mut_dat))
          bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e) ape::fastme.ols(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
      }
      branch.id <- readPhyloTree(matTree)
      
      mut.branches_types <- treeMutationalBranches(maf_data, branch.id, binary.matrix)
      mut.branches <- mut.branches_types$mut.branches
      branch.type <- mut.branches_types$branch.type
      
      phylo.tree <- new('phyloTree',
                        patientID = patient, tree = matTree, 
                        binary.matrix = binary.matrix, ccf.matrix = ccf.matrix, 
                        mut.branches = mut.branches, branch.type = branch.type,
                        ref.build = refBuild,
                        bootstrap.value = bootstrap.value, method = method)
      phyloTree_patient_list[[patient]] <- phylo.tree
  }
  
  if(length(phyloTree_patient_list) > 1){
      phyloTree_list <- new('phyloTreeList',phyloTree_patient_list)
      return(phyloTree_list)
  }else if(length(phyloTree_patient_list) == 1){
      return(phyloTree_patient_list[[1]])
  }else{
      return(NA)
  }
}