#' @title getPhyloTree
#' 
#' @import phangorn
#' @param a Maf object generated by readMaf function
#' @param method Approach to construct phylogenetic trees.Choose one of "NJ"(Neibor-Joining),"MP"(maximum parsimony),"ML"(maximum likelihood),""FASTME.ols" or "FASTME.bal". 
#' @param min.vaf the minimum value of vaf
#' @param max.vaf the maximum value of vaf
#' @param min.CCF the minimum value of CCF
#' @param bootstrap.rep.num bootstrap iterations.
#' 
#' 
#' @examples
#' maf.File <- system.file("extdata", "HCC6046.maf", package = "MesKit")
#' ccf.File <- system.file("extdata", "HCC6046.CCF.txt", package = "MesKit")
#' maf <- readMaf(mafFile=maf.File, refBuild="hg19")
#' njtree <- getPhyloTree(maf)
#' @return  a list of class PhyloTree
#' @exportClass phyloTree
#' @export getPhyloTree


# set NJtree object
getPhyloTree <- function(maf, 
                      method = "NJ",
                      min.vaf = 0.02, 
                      max.vaf = 1,
                      min.CCF = NULL,
                      bootstrap.rep.num = 100){
  
  method.options <- c("NJ","MP","ML","FASTME.ols","FASTME.bal")
  if(!method %in% method.options){
      stop("method can only be either 'NJ','ML' or 'MP','FASTME.ols','FASTME.bal'")
  }
  maf.dat <- maf@data
  refBuild <- maf@ref.build
  maf.dat$Patient_ID <- as.character(maf.dat$Patient_ID)
  dat.list <- split(maf.dat, maf.dat$Patient_ID)
  phyloTree.list <- list()
  phyloTree.list <- lapply(dat.list, doGetPhyloTree,
                           refBuild = refBuild,
                           method = method,
                           min.vaf = min.vaf,
                           max.vaf = max.vaf,
                           min.CCF = min.CCF,
                           bootstrap.rep.num = bootstrap.rep.num)
  return(phyloTree.list)
}

byMP <- function(mut_dat){
    matTree <- nj(dist.gene(mut_dat))
    tree_dat <- phangorn::as.phyDat(mut_dat, type="USER", levels = c(0, 1))
    tree_pars <- suppressMessages(phangorn::optim.parsimony(matTree, tree_dat,trace = F)) 
    matTree <- phangorn::acctran(tree_pars, tree_dat)
    return(matTree)
}

byML <- function(mut_dat){
    matTree <- nj(dist.gene(mut_dat))
    tree_dat <- phangorn::as.phyDat(mut_dat, type="USER", levels = c(0, 1))
    fitJC <- phangorn::pml(matTree, tree_dat)
    fitJC <- try(phangorn::optim.pml(fitJC,control = phangorn::pml.control(trace = F))) 
    matTree <- fitJC$tree
    return(matTree)
}

doGetPhyloTree <- function(patient.dat = NULL,
                           refBuild = NULL,
                           method = "NJ",
                           min.vaf = 0.02, 
                           max.vaf = 1,
                           min.CCF = NULL,
                           bootstrap.rep.num = 100){
    if(!is.null(min.CCF)){

        if("CCF" %in% colnames(patient.dat)){
            patient.dat <- patient.dat[CCF > min.CCF, ]
        }
        else{
            warnings("min.CCF argument only works when CCF data is provided!")

        }
    }
    patient.dat <- patient.dat[which(patient.dat$VAF > min.vaf & patient.dat$VAF < max.vaf), ]
    ## information input
    binary.matrix <- getMutMatrix(patient.dat, use.ccf = FALSE)
    if("CCF" %in% colnames(patient.dat)){
        ccf.matrix <- getMutMatrix(patient.dat, use.ccf = TRUE)
    }else{
        ccf.matrix <- matrix() 
    }
    mut_dat <- t(binary.matrix)
    if(method == "NJ"){
        matTree <- nj(dist.gene(mut_dat))
        bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e)nj(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
    }
    else if(method == "MP"){
        matTree <- byMP(mut_dat)
        bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e)byMP(e),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100 
    }
    else if(method == "ML"){
        matTree <- byML(mut_dat)
        bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e)byML(e),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
    }
    else if(method == "FASTME.bal"){
        matTree <- ape::fastme.bal(dist.gene(mut_dat))
        bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e) ape::fastme.bal(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
    }
    else if(method == "FASTME.ols"){
        matTree <- ape::fastme.ols(dist.gene(mut_dat))
        bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e) ape::fastme.ols(dist.gene(e)),B = bootstrap.rep.num,quiet = T)/(bootstrap.rep.num)*100
    }
    branchAlias <- readPhyloTree(matTree)
    mut.branches <- .treeMutationalBranches(patient.dat, branchAlias, binary.matrix)
    patientID <- unique(patient.dat$Patient_ID)
    phylo.tree <- new('phyloTree', patientID = patientID, tree = matTree, 
                      binary.matrix = binary.matrix, ccf.matrix = ccf.matrix, 
                      mut.branches = mut.branches, refBuild = refBuild,
                      bootstrap.value = bootstrap.value, method = method)
    return(phylo.tree)
}
#Prevent class 'phylo' from not existing
setClass('phylo')
setClass('phyloTree', slots = c(tree = 'phylo', patientID = 'character', binary.matrix = 'matrix', mut.branches = 'list', ccf.matrix = 'matrix', refBuild = 'character',
                                bootstrap.value = 'numeric', method = 'character'))

