#' getTMB
#' @description Calculate tumor mutational burden(TMB) and VAF value could be filtered with minvaf and maxvaf.
#' 
#' @param maf the classMaf object generated by readMaf.
#' @param tsb Specify Tumor_Sample_Barcodes for single or all samples from maf of the patient. Default: NULL, which means that output all samples' TMB Score.
#' @param minvaf  Default: 0. Option: on the scale of 0 to 0.02. Filter low frequency variants.
#' @param maxvaf Default: 0. Option: on the scale of 0 to 1. Filter extremely high frequency variants.
#' @return a list containing MATH scores of all/selected samples.
#' 
#' @examples
#' getTMB(maf, minvaf=0.02, maxvaf=1)
#' getTMB(maf, tsb = "SRR3670035))
#' 
#' @export getTMB

## TMB main function (actually could be combined as a lighter tool)
## Tumor burden calculation
calTumorBurden <- function(vafColumnMATH){
    VAF = VAF[!is.na(VAF)] 
    TMB <- round(length(VAF)/40, digits = 3)
    return(TMB)
}

getTMB <- function(maf, tsb=NULL, minvaf=0.02, maxvaf=1){
    ## get vaf-related infomation
    mafData <- maf@data
  
    if (is.null(tsb)){
        tsb = unique(mafData$Tumor_Sample_Barcode)
    }     

    ## get vaf-related infomation
    TMB.df <- mafData %>%
        dplyr::filter(Tumor_Sample_Barcode %in% tsb) %>%
        dplyr::filter(VAF> minvaf & VAF < maxvaf) %>%
        dplyr::group_by(PatientID, Tumor_Sample_Barcode) %>%
        dplyr::summarise(TMB = calTumorBurden(VAF))

    return(TMB.df)

    message("Calculation of TMB is done!")
}





