#load packages
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(pathview)
library(topGO)
library(DOSE)
library(dplyr)
library(gridExtra)
options(stringsAsFactors = T)
options(bitmapType='cairo')
options(warn = -1)

#' Use R code to do the GO analysis.
#'
#' @param njtree a njtree object generated by NJtree.R
#' @param GO.type One of "BP", "MF", and "CC" subontologies, or "ALL" for all three. Default type="ALL"
#' @param pval Cutoff value of pvalue. Default pval=0.05
#' @param qval Cutoff value of qvalue. Default qval=0.2
#' @param pAdjustMethod one of "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". Default pAdjustMethod="BH"
#' @param savePlot logical. Whether to print the dotplot or barplot of GO result.
#' @param plotType one of "dot" , "bar"
#' @param showCategory category numbers
#' @return
#' @export a .xls file contains or picture of GO analysis result
#' @examples 
#' GO.njtree(njtree, GO.type = "BP", savePlot = T)
#' 

GO_analysis <- function(genes = NULL, GO.type = GO.type, pval = pval, pAdjustMethod = pAdjustMethod,
                        qval = qval, outdir = outdir, patientID = patientID, Name = Name, savePlot = savePlot, 
                        plotType = plotType, showCategory = showCategory){
  GO.type <- toupper(GO.type)
  GO.type <- match.arg(GO.type, c("BP", "MF", "CC", "ALL"))
  
  ego <- enrichGO(gene          = genes,
                  OrgDb         = org.Hs.eg.db,
                  keyType       = 'SYMBOL',
                  ont           = GO.type,
                  pvalueCutoff  = pval,
                  pAdjustMethod = pAdjustMethod,
                  qvalueCutoff  = qval
  )
  
  ego@result <- ego@result[which(ego@result$pvalue < pval && ego@result$qvalue < qval), ]
  
  if (!is.null(ego) && nrow(ego@result) > 0){
    if(Name == "All"){
      ego@result$Case <- patientID
    }
    else{
      ego@result$branch <- Name
    }
  }
  return(ego)
}



GO.njtree.shiny <- function(njtree, GO.type = "ALL", pval = 0.05, pAdjustMethod = "BH", 
                      qval = 0.2, outdir = NULL, savePlot = TRUE, plotType = "dot", showCategory = NULL){
  branches <- njtree@mut_branches
  patientID <- njtree@patientID
  
  if(is.null(outdir)){
    outdir <- getwd()
  }
  
  GO.branch.result <- data.frame()
  all.genes <- c()
  grob.list <- list(NULL)
  x <- 1
  for (i in 1:length(branches)){
    branch <- branches[[i]]
    sampleID <- names(branches)[i]
    #split the gene symbol by ","
    geneSymbol <- unique(unlist(strsplit(as.character(branch$Hugo_Symbol), split = ",")))
    all.genes <- unique(c(all.genes, geneSymbol))
    ego.branch <- GO_analysis(geneSymbol, GO.type, pval, pAdjustMethod,
                qval, outdir, patientID, sampleID, savePlot, plotType, showCategory)
      if (is.null(showCategory)){
        showCategory = nrow(ego.branch@result)
      }
      
      str_length = max(nchar(ego.branch@result$Description))
      str_height = showCategory
      
      if (str_height > 15){
        fig.height = str_height/3
      }
      else{fig.height = 5}
      # plot result
      if(nrow(ego.branch@result)!=0){
        if (plotType == "dot"){
        GO.plot <- dotplot(ego.branch, showCategory = showCategory)+ggtitle(sampleID)
        if(savePlot){
          ggsave(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_barplot.pdf", sep = ""),plot = GO.plot,width = 3+(str_length)/10, height = fig.height)
        }
      }
        else if (plotType == "bar"){
        GO.plot <- barplot(ego.branch, showCategory = showCategory)+ggtitle(sampleID)
        if(savePlot){
          ggsave(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_barplot.pdf", sep = ""),plot = GO.plot,width = 3+(str_length)/10, height = fig.height)
        }
      }
        grob.list[[x]] <- GO.plot
        x <- x+1
      }
    ego.branch.result <- rbind(GO.branch.result, ego.branch@result)
  }
  
  ego.all <- GO_analysis(all.genes, GO.type, pval, pAdjustMethod,
                           qval, outdir, patientID, Name = "All", savePlot, plotType, showCategory)
  ego.all.result <- ego.all@result
  if (is.null(showCategory)){
    showCategory = nrow(ego.all.result)
  }
  
  str_length = max(nchar(ego.all.result$Description))
  str_height = showCategory
  
  if (str_height > 15){
    fig.height = str_height/3
  }else{fig.height = 5}
  
  if(nrow(ego.all.result) != 0){
    if (plotType == "dot"){
    GO.plot <- dotplot(ego.all, showCategory = showCategory) + ggtitle(sampleID)
    if(savePlot){
      ggsave(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_barplot.pdf", sep = ""),plot = GO.plot,width = 3+(str_length)/10, height = fig.height)
    }
  }else if (plotType == "bar"){
    GO.plot <- barplot(ego.all, showCategory = showCategory)+ ggtitle(sampleID)
    if(savePlot){
      ggsave(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_barplot.pdf", sep = ""),plot = GO.plot , width = 3+(str_length)/10, height = fig.height)
    }
  }
    grob.list[[length(grob.list)+1]] <- GO.plot
  }
  
  
  if(is.null(ego.branch.result)){
    message("0 enriched terms found in all of the shared or private mutations")
  }else{
    write.table(ego.branch.result, file = paste(outdir, "/",  patientID, "_GO_branch_enrich.xls",sep = ""),
                sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)    
  }
  
  if(is.null(ego.all.result)){
    message(paste( "0 enriched terms found in mutated genes in all tumor samples from Case", patientID))
  }
  else{
    write.table(ego.all.result, file = paste(outdir, "/",  patientID, "_GO_all_enrich.xls",sep = ""),
                sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
  }
  if(length(grob.list) == 1){
    grid.arrange(grobs = grob.list,ncol =1)
  }
  else if(length(grob.list) > 1){
    grid.arrange(grobs = grob.list,ncol =2 )
  }
  else if(length(grob.list) == 0){
    print('nothing')
  }
}

