#load packages
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(pathview)
library(topGO)
library(dplyr)


options(stringsAsFactors = FALSE)
options(bitmapType='cairo')
options(warn = -1)

#' Use R code to do the GO analysis.
#'
#' @param njtree a njtree object generated by NJtree.R
#' @param GO.type One of "BP", "MF", and "CC" subontologies, or "ALL" for all three. Default type="ALL"
#' @param pval Cutoff value of pvalue. Default pval=0.05
#' @param qval Cutoff value of qvalue. Default qval=0.2
#' @param pAdjustMethod one of "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". Default pAdjustMethod="BH"
#' @param savePlot logical. Whether to print the dotplot or barplot of GO result.
#' @param plotType one of "dot" , "bar"
#' @param showCategory category numbers
#' @return
#' @export a .xls file contains or picture of GO analysis result
#' @examples 
#' GO.njtree(njtree, GO.type = "BP", savePlot = T)
#' 


GO_analysis <- function(genes = NULL, GO.type = GO.type, pval = pval, pAdjustMethod = pAdjustMethod,
 qval = qval, outdir = outdir, patientID = patientID, Name = Name, savePlot = savePlot, 
 plotType = plotType, showCategory = showCategory){
  GO.type <- toupper(GO.type)
  GO.type <- match.arg(GO.type, c("BP", "MF", "CC", "ALL"))

  ego <- enrichGO(gene          = genes,
                  OrgDb         = org.Hs.eg.db,
                  keyType       = 'SYMBOL',
                  ont           = GO.type,
                  pvalueCutoff  = pval,
                  pAdjustMethod = pAdjustMethod,
                  qvalueCutoff  = qval
                  )

  ego@result <- ego@result[which(ego@result$pvalue < pval && ego@result$qvalue < qval), ]

  if (!is.null(ego) && nrow(ego@result) > 0){
    if(Name == "All"){
      ego@result$Case <- patientID
    }
    else{
      ego@result$branch <- Name
    }
                 
    if (savePlot){
      if (is.null(showCategory)){
        showCategory = nrow(ego@result)
      }

      str_length = max(nchar(ego@result$Description))
      str_height = showCategory

      if (str_height > 15){
        fig.height = str_height/3
      }else{fig.height = 5}
 
      if (plotType == "dot"){
        pdf(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_dotplot.pdf", sep = ""), width = 3+(str_length)/10, height = fig.height)
        print(dotplot(ego, showCategory = showCategory))
        dev.off()
      }
      else if (plotType == "bar"){
        pdf(paste(outdir, "/", patientID, "_", Name, "_GO_", GO.type, "_barplot.pdf", sep = ""), width = 3+(str_length)/10, height = fig.height)
        print(barplot(ego, showCategory = showCategory))
        dev.off()
      }
    }
  }
  return(ego@result)
}



GO.njtree <- function(njtree, GO.type = "ALL", pval = 0.05, pAdjustMethod = "BH", 
  qval = 0.2, outdir = NULL, savePlot = TRUE, plotType = "dot", showCategory = NULL){
  branches <- njtree@mut_branches
  patientID <- njtree@patientID

  if(is.null(outdir)){
    outdir <- getwd()
  }
 
  GO.branch.result <- data.frame()
  all.genes <- c()
  for (i in 1:length(branches)){
    branch <- branches[[i]]
    sampleID <- names(branches)[i]
    #split the gene symbol by ","
    geneSymbol <- unique(unlist(strsplit(as.character(branch$Hugo_Symbol), split = ",")))
    all.genes <- unique(c(all.genes, geneSymbol))

    GO.branch.result <- rbind(GO.branch.result, GO_analysis(geneSymbol, GO.type, pval, pAdjustMethod,
     qval, outdir, patientID, sampleID, savePlot, plotType, showCategory))
  }

  GO.result <- GO_analysis(all.genes, GO.type, pval, pAdjustMethod,
     qval, outdir, patientID, Name = "All", savePlot, plotType, showCategory)
  
  if(is.null(GO.branch.result)){
    message("0 enriched terms found in all of the shared or private mutations")
  }
  else{
  write.table(GO.branch.result, file = paste(outdir, "/",  patientID, "_GO_branch_enrich.xls",sep = ""),
            sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)    
  }

  if(is.null(GO.result)){
    message(paste( "0 enriched terms found in mutated genes in all tumor samples from Case", patientID))
  }
  else{
  write.table(GO.result, file = paste(outdir, "/",  patientID, "_GO_all_enrich.xls",sep = ""),
            sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
  }
}

