#' plot the corresponding binary heatmap| ccf heatmaf of the NJtree
#'
#' @param Maf an \code{\link{maf}} object generated by \code{\link{read.maf}
#' @param use.ccf logical. Whether to print the binary heatmap with ccf values. Defaults to FALSE, print the binary heatmap without ccf value
#' @return binary mutation heatmap or mutation CCF heatmap
#'
#'@export mut.heatmap
#'
#' @examples
#' mut.heatmap(njtree)
#' mut.heatmap(njtree, use.ccf = TRUE)
#' 

## there are two @param use.ccf..
# @param use.ccf Use mutation CCF for heatmap painting. Default FALSE.

heatmap_input <- function(mat, type){
  names <- c("mutation", "sample", "Mutation")
  if(type == "CCF"){
    names <- c("mutation", "sample", "CCF")
  }
  
  mut_dat <- melt(mat)
  colnames(mut_dat) <- names
  return(mut_dat)
}


mut.heatmap <- function(njtree, use.ccf = FALSE){
  patientID <- njtree@patientID
  mut_sort <- njtree@mut_sort
  ccf_sort <- njtree@ccf_sort
  mat <- mut_sort
  type  <- "Mutation"
  if(use.ccf){
    type <- "CCF"
    mat <- ccf_sort
    if(is.null(ccf)){
      stop("njtree@ccf_sort is NULL. No ccf data was found when readMaf")
    }
  }
  
  mut_dat <- heatmap_input(mat, type = type)
  mut_dat$sample <- factor(mut_dat$sample, levels =unique(mut_dat$sample))
  p_basic <- ggplot(mut_dat, aes(sample, mutation)) +
    labs(x = "", y = "") + theme_bw() +
    theme(panel.border = element_blank()) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(axis.text.y = element_blank()) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 9, hjust = 1, color = "black")) +
    theme(axis.ticks = element_blank()) +
    theme(legend.title = element_text(size = 12, face = "bold", color = "black")) +
    theme(legend.text = element_text(size = 10, face = "bold", color = "black")) +
    theme(legend.position = "right" ) +
    labs(fill = type) + scale_y_continuous(expand = c(0,0))+
    theme(plot.margin=unit(c(0,0,1.5,0),"cm"))
  if(use.ccf){
    p <- p_basic + geom_tile(aes(fill = mut_dat$CCF)) + scale_fill_gradient(low = "#deebf7", high = "#08306b", na.value="black", limit=c(0, 1))
    #ggsave(paste(patientID, "_mut_CCF.pdf", sep = ""), p, width = 4.5, height = 6.5)
  }
  if(!use.ccf){
    p <- p_basic + geom_tile(aes(fill = as.factor(mut_dat$Mutation))) + scale_fill_manual(values = c("#deebf7", "#08306b"))
    #ggsave(paste(patientID, "_mut.pdf", sep = ""), p, width = 4.5, height = 6.5)
  }
  return(p)
}


