#' Visualize genetic heterogeneity between samples based on Jaccard Similarity coefficients of variants
#' 
#' @import corrplot
#' 
#' @description The Jaccard similarity coefficient is defined as the ratio of shared variants to all 
#' (shared plus discordant) variants for two samples. 
#' 
#' @param maf object generated by readMaf function
#' @return the grapgical display of correlation matrix via Jaccard similarity coefficient method
#''
#' @examples
#' JaccardIndex(maf)
#' @export JaccardIndex


JaccardIndex <- function(maf, type = "lower"){
	dat <- maf@data
	TSBs <- unique(dat$Tumor_Sample_Barcode)

	variants.list <- list()
	for (tsb in TSBs){
		dat.tsb <- dat[which(dat$Tumor_Sample_Barcode == tsb),]
		variants.list[[tsb]] <- paste(dat.tsb$Hugo_Symbol, dat.tsb$Chromosome, dat.tsb$Start_Position, dat.tsb$Variant_Type,
		dat.tsb$Reference_Allele, dat.tsb$Tumor_Seq_Allele2, sep=":")
	}

	Jaccard.mat <- diag(1, nrow = length(TSBs), ncol = length(TSBs))
	colnames(Jaccard.mat) <- TSBs
	rownames(Jaccard.mat) <- TSBs
	for(i in 1:(length(TSBs)-1)){
		for(j in (i+1):length(TSBs)){
			variants.i <- unlist(variants.list[TSBs[[i]]])
			variants.j <- unlist(variants.list[TSBs[[j]]])
			Jaccard.mat[i,j] <- length(intersect(variants.i, variants.j))/length(union(variants.i,variants.j))
			Jaccard.mat[j,i] <- Jaccard.mat[i,j]
		}
	}
	corrplot::corrplot(Jaccard.mat, type = type, is.corr = F, method="pie", outline = FALSE, tl.col = "black",
	  addCoef.col = "grey", col = RColorBrewer::brewer.pal(10,"PuOr"), cl.lim = c(0, 1), add = FALSE, tl.cex = 0.9)
}
