#' calJSI
#'
#' @description The Jaccard similarity index (JSI) is applied to distinguish monoclonal versus polyclonal seeding in metastases
#' @references Hu Z, Li Z, Ma Z, Curtis C: Pan-cancer analysis of clonality and the timing of systemic spread in paired primary tumors and metastases. bioRxiv 2019.
#' @param maf a Maf object generated by readMaf function
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param plot logical (Default:TRUE). Whether to show the plot, default TRUE
#' @param use.circle logical (Default:TRUE). Whether to use "circle" as visualization method of correlation matrix
#' @param title the title of the plot, default is "Jaccard similarity"
#'
#' @examples
#' calJSI(maf)
#' @return correlation matrix and heatmap via Jaccard similarity coefficient method
#' @export calJSI

JSI_dist <- function(df){

    df <- tidyr::pivot_wider(df,
            names_from = Tumor_Sample_Barcode,
            values_from = VAF_adj,
            values_fill = list(VAF_adj = 0)
    ) %>%
    dplyr::select(-mutation_id) 

    Status <- df$Status
    df <- subset(df, select=-Status)

    dist <- diag(1, nrow = ncol(df), ncol = ncol(df))
    for (i in 1:(ncol(df) - 1)) {
        for (j in (i + 1):ncol(df)) {

            pair <- data.frame(Status, df[,i], df[,j]) %>%
                dplyr::filter(rowSums(.[,-1])!=0) %>%
                `colnames<-`(c("Status","S1", "S2")) %>%
                data.table::setDT()

            PC_1 <- nrow(pair[Status=="Clonal" & S1>0 & S2==0])
            PC_2 <- nrow(pair[Status=="Clonal" & S2>0 & S1==0])
            SS_12 = nrow(pair[Status=="Subclonal" & S1>0 & S2>0])

            dist[i, j] <- dist[j, i] <- SS_12/(PC_1+PC_2+SS_12) 
        }
    }
    rownames(dist) <- colnames(df)
    colnames(dist) <- colnames(df)

    return(JSI.dist =  dist)
    }    

calJSI <- function(maf, patient.id = NULL, plot = TRUE, 
    use.circle = TRUE, title = "Jaccard similarity") {

    mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Error: calculation of AUC of CCF requires CCF data." ,
            "No CCF data was found when generate Maf object."))
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
    }

    JSI.dist <- mafData %>%
        tidyr::unite(
            "mutation_id",
            c(
                "Chromosome",
                "Start_Position",
                "Reference_Allele",
                "Tumor_Seq_Allele2"
            ),
            sep = ":",
            remove = FALSE
        ) %>%
        dplyr::select(
            mutation_id,
            Tumor_Sample_Barcode,
            Patient_ID,
            Status,
            VAF_adj) %>% 
        dplyr::group_by(Patient_ID) %>%
        dplyr::group_map(~JSI_dist(.), keep = FALSE) %>%
        rlang::set_names(patient.id)

    JSI.plot = list()
    if(plot){
        for(i in 1:length(JSI.dist)){
            JSI.plot[[i]] <- plotCorr(
                JSI.dist[[i]], 
                use.circle = use.circle,
                title = paste0(title, " of patient ", patient.id[i])
                )
        }
        names(JSI.plot) <- patient.id
    }

   return(list(JSI.dist = JSI.dist, JSI.plot =  JSI.plot))  

}

