#' A Multifunctional MATH Calculator
#' @description Calculate MATH score and present results in different ways 
#' determined by parameters. VAF can be on the scale 0-1 and you could filter 
#' VAF with minvaf and maxvaf.
#' 
#' @param maf the classMaf object generated by readMaf.
#' @param tsb specify excute ITH asessment for single or all samples from the same patient(Tumor_Sample_Barcodes) 
#' @param minvaf filter low frequency variants caused by sequencing error. Default 0. (on the scale of 0 to 1)
#' @param maxvaf filter high frequency variants due to copy number alterations or impure tumor. Default 1. (on the scale of 0 to 1)
#' @return MATH score list for all/selected samples or a MATH score value.
#' 
#' @examples
#' ## data information
#' maf.File <- system.file("extdata/multi_lesion/maf", "311252.maf", package = "Meskit")
#' maf <- readMaf(patientID="311252", mafFile=maf.File, sampleInfoFile=sampleInfo.File, refBuild="hg19")
#' ## generate MATH scores for all tsbs
#' mathScore(maf, tsb=c("All"), minvaf=0, maxvaf=1)
#' ## generate MATH score for specific tsbs
#' mathScore(maf, tsb=c("311252-S"))
#' mathScore(maf, tsb=c("311252-S", "311252-V"))
#' 
#' @export mathScore
#' 

## MATH Score main function
mathScore <- function(maf, tsb=c("All"), minvaf=0, maxvaf=1){
    ## get vaf-related infomation
    mafData <- maf@data
    dataHugoSymbol <- mafData$Hugo_Symbol
    dataVaf <- mafData$VAF
    dataTsb <- data.frame(mafData$Tumor_Sample_Barcode)
    vafInputMt <- data.frame(dataHugoSymbol, dataVaf, dataTsb)
    colnames(vafInputMt) <- c("Hugo_Symbol", "VAF", "Tumor_Sample_Barcode")
    ## get all sample names
    tsbLs <- data.frame(unique(vafInputMt$Tumor_Sample_Barcode))
    
    ## MATH results for one/all sample
    if (any(tsb == c("All"))){
        ## list all samples' MATH scores
        mathOFA <- .multiSampleMATH(vafInputMt, tsbLs, minvaf, maxvaf)
        mathAll <- .patientMATH(vafInputMt, tsbLs, minvaf, maxvaf)
        mathAll <- data.frame(Tumor_Sample_Barcode=maf@patientID, 
                              MATH_score=c(mathAll$MATH_score), 
                              Tumor_Burden=c(mathAll$Tumor_Burden))
        colnames(mathOFA) <- c("Tumor_Sample_Barcode", "MATH_score", 
                               "TMB(mutations/Mb)")
        mathResult <- list(patientLevel=mathAll, sampleLevel=mathOFA)
        return(mathResult)
    } else{
        ## calculate specific samples' MATH score
        tsbLs <- data.frame(tsb)
        mathSp <- .multiSampleMATH(vafInputMt, tsbLs, minvaf, maxvaf)
        mathAll <- .patientMATH(vafInputMt, tsbLs, minvaf, maxvaf)
        mathAll <- data.frame(Tumor_Sample_Barcode=maf@patientID, 
                              MATH_score=c(mathAll$MATH_score), 
                              Tumor_Burden=c(mathAll$Tumor_Burden))
        colnames(mathSp) <- c("Tumor_Sample_Barcode", "MATH_score", 
                              "TMB(mutations/Mb)")
        mathResult <- list(patientLevel=mathAll, sampleLevel=mathSp)
        return(mathResult)
    }
    message("MATH Score Calculation Done!")
}


## Data cleaning
.dataClean <- function(vafInputMt, tsb, minvaf, maxvaf){
    vafColumn <- vafInputMt[which(
        vafInputMt$Tumor_Sample_Barcode == tsb), ]$VAF
    vafColumn <- vafColumn[which(
        !is.na(vafColumn))][which(
            vafColumn > minvaf & vafColumn < maxvaf)]
    vafColumn <- as.numeric(
        as.character(vafColumn))[which(!is.na(vafColumn))]
    return(vafColumn)
}

## MATH Caculation
.calMATH <- function(vafColumn){
    MAD <- 1.4826*median(abs(vafColumn - median(vafColumn)))
    MATH <- 100 * MAD / median(vafColumn)
    return(round(MATH, digits=3))
}

## Tumor burden Caculation
.calTumorBurden <- function(vafColumn){
    tumorBurden <- length(vafColumn)/40
    return(tumorBurden)
}

## MATH multi-sample process
.multiSampleMATH <- function(vafInputMt, tsbLs, minvaf, maxvaf){
    samplesMATH <- data.frame()
    for (counter in seq_along(tsbLs[,1])){
        for (sampleNameMt in tsbLs){
            vafColumn <- .dataClean(
                vafInputMt, 
                as.character(sampleNameMt)[counter], 
                minvaf, maxvaf)
            sampleMATH <- data.frame(
                as.character(sampleNameMt)[counter], 
                .calMATH(vafColumn), .calTumorBurden(vafColumn))
            samplesMATH <- rbind(samplesMATH, sampleMATH)
        }
    }
    colnames(samplesMATH) <- c("Tumor_Sample_Barcode", "MATH_score", 
                               "Tumor_Burden")
    return(samplesMATH)
}

## MATH patient calcualtion
.patientMATH <- function(vafInputMt, tsbLs, minvaf, maxvaf){
    vafColumn <- vafInputMt$VAF
    tsbNum <- nrow(tsbLs)
    vafColumn <- vafColumn[which(
        !is.na(vafColumn))][which(
            vafColumn > minvaf & vafColumn < maxvaf)]
    vafColumn <- as.numeric(
        as.character(vafColumn))[which(
            !is.na(vafColumn))]
    result <- data.frame(MATH_score=.calMATH(vafColumn), 
                         Tumor_Burden=length(vafColumn)/40/tsbNum)
    return(result)
}
