#' @title mutHeatmap
#' @description plot the corresponding binary heatmap or ccf heatmaf of the phyloTree
#'
#' @param phyloTree a \code{\link{phyloTree}}} object generated by \code{\link{getPhyloTree}}
#' @param use.ccf logical. If FALSE (default), print a binary heatmap of mutations. Otherwise, print a cancer cell frequency (CCF) heatmap.
#' @param show.class.label logical. If TRUE, show labels for mutations classes on the heatmap.Default is TRUE.
#' 
#' @return heatmap of somatic mutations
#'
#'
#' @examples
#' mutHeatmap(phyloTree)
#' mutHeatmap(phyloTree, use.ccf = TRUE)
#'
#' @export mutHeatmap

mutHeatmap <- function(phyloTree, use.ccf = FALSE, show.class.label = TRUE){
    mut_sort <- phyloTree@binary.matrix
    row.names(mut_sort) <- 1:nrow(mut_sort)
    ccf_sort <- phyloTree@ccf.matrix
    row.names(ccf_sort) <- 1:nrow(ccf_sort)
    mat <- mut_sort
    type  <- "Mutation"
    if(use.ccf){
        type <- "CCF"
        mat <- ccf_sort
        if(is.null(ccf_sort)){
            stop("phyloTree@ccf.matrix is NULL. No ccf data was found when readMaf")
        }
    }
    shared.num <- ncol(mut_sort)-1
    if(1 %in% mut_sort[,"NORMAL"]){
        shared.num <- ncol(mut_sort) 
    }
    mutation.classes <- apply(mut_sort,1,function(x,shared.num){
        if(sum(x) == shared.num){
            return("Shared")
        }
        else if(sum(x) == 1){
            return("Private")
        }
        else{
            return("P-shared")
        }
    },shared.num = shared.num)
    mut_dat <- heatmap_input(mat, type = type, mutation.classes)
    
    ## the num of each mutation class
    classes.num <- c()
    classes.sum <- length(mutation.classes)
    ## annotation bar table
    annotation.bar <- data.frame()
    xmin <- max(mut_dat$xmax)
    xmax <- max(mut_dat$xmax) + max(mut_dat$xmax)- max(mut_dat$xmin)
    ymin <- min(mut_dat$ymin)
    classes.level <- unique(mutation.classes)
    for(class in classes.level){
        ymax <- max(mut_dat[mut_dat$class == class,]$ymax)
        sub <- c(xmin, xmax, ymin, ymax)
        annotation.bar <- rbind(annotation.bar, sub)
        ymin <- ymax
        ## percentage of class
        class.num <- length(which(mutation.classes == class))/classes.sum
        percentage <- paste0("\n",round(class.num,2)*100,"%")
        classes.num[class] <- percentage
    }
    colnames(annotation.bar) <- c("xmin","xmax","ymin","ymax")
    
    ## color of annotation bar
    class.all.colors <- c( "Shared" = "#00A087FF",
                           "P-shared" = "#8491B4FF",
                           "Private" = "#E64B35FF" )
    class.colors <- class.all.colors[classes.level]
    
    ## label of annotation bar
    classes.label <- paste0(classes.level,classes.num)
    
    p_basic <- ggplot() +
        labs(x = "", y = "") + theme_bw() +
        theme(panel.border = element_blank()) +
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        theme(axis.text.x = element_text(angle = 90, vjust = -3, size = 9, hjust = 0, color = "black"))+
        theme(axis.ticks = element_blank()) +
        theme(legend.title = element_text(size = 12, face = "bold", color = "black")) +
        theme(legend.text = element_text(size = 10, face = "bold", color = "black")) +
        theme(legend.position = "right" )+
        scale_y_continuous(expand = c(0,0))+
        scale_x_continuous(
            breaks = unique(mut_dat$xmin) + (unique(mut_dat$xmax) - unique(mut_dat$xmin))/2,
            labels = unique(mut_dat$sample),
            position = "top")+
        ## annotation bar
        geom_rect(data = annotation.bar,
                  mapping = aes(xmin = xmin,xmax = xmax,ymin = ymin, ymax = ymax),
                  fill = class.colors)
    if(show.class.label){
        p_basic <- p_basic + 
            geom_text(data = annotation.bar,
                      mapping = aes(x = annotation.bar$xmin + (annotation.bar$xmax-annotation.bar$xmin)/2,
                                    y = annotation.bar$ymin + (annotation.bar$ymax-annotation.bar$ymin)/2),
                      label = classes.label,
                      angle = 90)
    }
    if(use.ccf){
        p <- p_basic + 
            geom_rect(data = mut_dat,
                      mapping = aes(xmin = xmin,xmax = xmax,ymin = ymin, ymax = ymax,fill = CCF))+
            scale_fill_gradient(low = "#deebf7", high = "#08306b", na.value="black", limit=c(0, 1))
        
        #ggsave(paste(patientID, "_mut_CCF.pdf", sep = ""), p, width = 4.5, height = 6.5)
    }
    if(!use.ccf){
        mut_dat$Mutation <- as.character(mut_dat$Mutation)
        p <- p_basic + 
            geom_rect(data = mut_dat,
                      mapping = aes(xmin = xmin,xmax = xmax,ymin = ymin, ymax = ymax,fill = Mutation))+
            scale_fill_manual(values = c("#deebf7", "#08306b"))
        #ggsave(paste(patientID, "_mut.pdf", sep = ""), p, width = 4.5, height = 6.5)
    }
    
    return(p)
}

heatmap_input <- function(mat, type, mutation.classes){
    mat <- as.data.frame(mat)
    mut.num <- nrow(mat)
    sample.num <- ncol(mat)
    mat$mutation <- 1:nrow(mat)
    mat$class <- factor(mutation.classes, levels = unique(mutation.classes)) 
    mat <- dplyr::arrange(mat,class)
    mat$ymin <- seq(0, 5, 5/(mut.num-1))
    mat$ymax <- mat$ymin + 5/(mut.num-1)
    value.name <- "Mutation"
    if(type == "CCF"){
        value.name <- "CCF"
    }
    mut_dat <- reshape2::melt(mat,
                              id.vars = c("ymin","ymax","mutation","class"),
                              variable.name = "sample",
                              value.name = value.name)
    mut_dat$xmin <- rep(seq(0, 1, 1/(sample.num-1)) ,each = nrow(mat)) 
    mut_dat$xmax <- mut_dat$xmin + 1/(sample.num-1)
    mut_dat$sample <- factor(mut_dat$sample, levels =unique(mut_dat$sample))
    return(mut_dat)
}
