#' @title mutHeatmap
#' @description plot the corresponding binary heatmap or ccf heatmaf of the phyloTree
#'
#' @param phyloTree a \code{\link{phyloTree}}} object generated by \code{\link{getPhyloTree}}
#' @param use.ccf logical. If FALSE (default), print a binary heatmap of mutations. Otherwise, print a cancer cell frequency (CCF) heatmap.
#' @return heatmap of somatic mutations
#'
#'
#' @examples
#' mutHeatmap(phyloTree)
#' mutHeatmap(phyloTree, use.ccf = TRUE)
#'
#' @export mutHeatmap

mutHeatmap <- function(phyloTree, use.ccf = FALSE){
    patientID <- phyloTree@patientID
    mut_sort <- phyloTree@binary.matrix
    row.names(mut_sort) <- 1:nrow(mut_sort)
    ccf_sort <- phyloTree@ccf.matrix
    row.names(ccf_sort) <- 1:nrow(ccf_sort)
    mat <- mut_sort
    type  <- "Mutation"
    if(use.ccf){
        type <- "CCF"
        mat <- ccf_sort
        if(is.null(ccf_sort)){
            stop("phyloTree@ccf.matrix is NULL. No ccf data was found when readMaf")
        }
    }
    
    mut_dat <- heatmap_input(mat, type = type)
    mut_dat$sample <- factor(mut_dat$sample, levels =unique(mut_dat$sample))
    p_basic <- ggplot(mut_dat, aes(sample, mutation)) +
        labs(x = "", y = "") + theme_bw() +
        theme(panel.border = element_blank()) +
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
        theme(axis.text.y = element_blank()) +
        theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 9, hjust = 1, color = "black")) +
        theme(axis.ticks = element_blank()) +
        theme(legend.title = element_text(size = 12, face = "bold", color = "black")) +
        theme(legend.text = element_text(size = 10, face = "bold", color = "black")) +
        theme(legend.position = "right" ) +
        labs(fill = type) + scale_y_continuous(expand = c(0,0))+
        theme(plot.margin=unit(c(0,0,1.5,0),"cm"))
    if(use.ccf){
        p <- p_basic + geom_tile(aes(fill = mut_dat$CCF)) + scale_fill_gradient(low = "#deebf7", high = "#08306b", na.value="black", limit=c(0, 1))
        #ggsave(paste(patientID, "_mut_CCF.pdf", sep = ""), p, width = 4.5, height = 6.5)
    }
    if(!use.ccf){
        p <- p_basic + geom_tile(aes(fill = as.factor(mut_dat$Mutation))) + scale_fill_manual(values = c("#deebf7", "#08306b"))
        #ggsave(paste(patientID, "_mut.pdf", sep = ""), p, width = 4.5, height = 6.5)
    }
    return(p)
}

heatmap_input <- function(mat, type){
  names <- c("mutation", "sample", "Mutation")
  if(type == "CCF"){
    names <- c("mutation", "sample", "CCF")
  }
  
  mut_dat <- melt(mat)
  colnames(mut_dat) <- names
  return(mut_dat)
}

