#' testNeutral
#' @description Evaluat whether a tumor follows neutral evolution or under strong selection
#' during the growth based on variant frequency distribution (VAF) of subclonal 
#' The subclonal mutant allele frequencies of a follow a simple power-law distribution predicted by neutral growth.  
#' 
#' @references Williams MJ, Werner B, Barnes CP, Graham TA, Sottoriva A. Identification of neutral tumor evolution across cancer types. 
#' Nat Genet. 2016;48(3):238–244. doi:10.1038/ng.3489
#' @param maf the Maf object generated by readMaf
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param min.depth the minimun depth of coverage. Defalut: 10
#' @param R2.threshold a threshod of R2 to decide whether a tumor follows neutral evolution. Default: 0.98
#' @examples
#' testNeutral(maf)
#' @export testNeutral
testPowerLaw <- function(df, R2.threshold){

	subPowerLaw <- function(sample.df){

		sample.id <- unique(sample.df$Tumor_Sample_Barcode)
    	sample.df <- sample.df %>%
    		dplyr::filter(
    			Status == "Subclonal" & 
    			Ref_allele_depth + Alt_allele_depth > min.depth &
    			!is.na(VAF_adj)
    		)  

		if(nrow(sample.df) == 0){
			R2 = NA
			warning(paste0("Sample ", sample.id, ": There is no eligable mutations can be used."))
		}else{
			max.vaf <- max(sample.df$VAF_adj)
			min.vaf <- min(sample.df$VAF_adj)
	
			breaks = ceiling((max.vaf - min.vaf)/0.01)
			vafCount =  hist(1/sample.df$VAF_adj, breaks = breaks, plot = F)
			vafCumsum <- data.frame(vafCount$breaks, c(0,cumsum(vafCount$counts)))
      		lmLine = summary(lm(vafCumsum[, 2] ~ vafCumsum[, 1]))
      		R2 = lmLine$adj.r.squared
	      
		}
	
		return(R2)		
	}

	

	patient.R2 <- df %>%
		dplyr::group_by(Tumor_Sample_Barcode) %>%
		dplyr::group_map(~subPowerLaw(.), keep = TRUE) %>%
		unlist()

	neutralTest.out <- data.frame(
		Tumor_Sample_Barcods = unique(df$Tumor_Sample_Barcode), 
		R2 = patient.R2) %>%
		dplyr::mutate(Type = dplyr::if_else(
			R2 >= R2.threshold,
			"neutral",
			"non-neutral"))


	return(neutralTest.out)   	

}


testNeutral <- function(maf, patient.id = NULL, min.depth = 10, R2.threshold= 0.98){
	
	mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Error: inferring whether a tumor follows neutral evolution requires CCF data.",
            "No CCF data was found when generate Maf object."))
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
    }

    R2.list <- mafData %>%
    	dplyr::group_by(Patient_ID) %>%
    	dplyr::group_map(~testPowerLaw(., R2.threshold), keep = TRUE) %>%
    	rlang::set_names(patient.id)    	

    return(R2.list)
}

