#' plot the corresponding binary heatmap| ccf heatmaf of the NJtree
#'
#' @param Maf an \code{\link{maf}} object generated by \code{\link{read.maf}
#' @param is.ccf Use mutation CCF for heatmap painting. Default FALSE.
#' @param use.indel logical. Whether to uses all variants irrespective of values in Mutation_Status.Defaults to FALSE, only use somatic mutations.
#' @param use.ccf logical. Whether to print the binary heatmap with ccf values. Defaults to FALSE, print the binary heatmap without ccf value
#' @return binary mutation heatmap or mutation CCF heatmap
#'
#' @examples
#' mut.heatmap(njtree, use.indel = F)
#' mut.heatmap(njtree, use.indel = F, use.ccf = TRUE)


heatmap_input <- function(mat, type){
  names <- c("mutation", "sample", "Mutation")
  if(type == "CCF"){
    names <- c("mutation", "sample", "CCF")
    }

  mut_dat <- melt(mat)
  colnames(mut_dat) <- names
  return(mut_dat)
}


mut.heatmap <- function(njtree, use.ccf = FALSE){
  patientID <- maf@patientID
  mut_sort <- njtree@mut_sort
  ccf_sort <- njtree@ccf_sort

  type  <- "Mutation"
  if(use.ccf){
    type <- "CCF"
    if(is.null(ccf)){
      stop("njtree@ccf_sort is NULL. No ccf data was found when readMaf")
    }
  }

  mut_dat <- heatmap_input(maf, use.indel = use.indel, use.ccf = use.ccf, ccf = ccf, ccf.mutation.id = ccf.mutation.id, ccf.mutation.sep = ccf.mutation.sep)
  mut_dat$sample <- factor(mut_dat$sample, levels =unique(mut_dat$sample))
  p_basic <- ggplot(mut_dat, aes(sample, mutation)) +
    labs(x = "", y = "") + theme_bw() +
    theme(panel.border = element_blank()) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(axis.text.y = element_blank()) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1,size = 10, hjust = 1, face = "bold", color = "black")) +
    theme(axis.ticks = element_blank()) +
    theme(legend.title = element_text(size = 12, face = "bold", color = "black")) +
    theme(legend.text = element_text(size = 10, face = "bold", color = "black")) +
    theme(legend.position = "right" ) +
    labs(fill = type) + scale_y_continuous(expand = c(0,0))

  if(use.ccf){
    p <- p_basic + geom_tile(aes(fill = mut_dat$CCF)) + scale_fill_gradient(low = "grey", high = "red", na.value="black", limit=c(0, 1))
    ggsave(paste(patientID, "_mut_CCF.pdf", sep = ""), p, width = 4.5, height = 6.5)
    }
  if(!use.ccf){
    p <- p_basic + geom_tile(aes(fill = as.factor(mut_dat$Mutation))) + scale_fill_manual(values = c("grey", "red"))
    #ggsave(paste(patientID, "_mut.pdf", sep = ""), p, width = 4.5, height = 6.5)
  }
  return(p)
}


