#' plotMutProfile
#'
#' @param maf the Maf object generated by readMaf
#' Classify SSNVs/Indels into Shared/P-shared/Private, Clonal/Subclonl
#' or Shared-Clonal/P-shared-Clonal/Private-Clonal/Shared-Subclonal/P-shared-SubClonal/Private-SubClonal 
#' @param driverGenesFile driver gene list. Default NULL
#' @param topGenesCount the number of genes print
#' @examples
#' plotMutProfile(maf, class = "SP", topGenesCount = 10)
#' @export plotMutProfile

genHeatmapPlotMatrix <- function(maf_data, topGenesCount = NULL) {
    if ("Driver_Mut" %in% colnames(maf_data)) {
        maf_data <- maf_data %>%
            dplyr::filter(Driver_Mut)
    }
    
    # long -> wider
    maf_data <- maf_data %>%
        dplyr::group_by(Hugo_Symbol) %>%
        dplyr::mutate(max_sample_count = max(unique_sample_count)) %>%
        dplyr::select(Hugo_Symbol,
                      Tumor_Sample_Barcode,
                      Mutation_Type,
                      max_sample_count) %>%
        tidyr::pivot_wider(
            names_from = Tumor_Sample_Barcode,
            values_from = Mutation_Type,
            values_fn = list(Mutation_Type = multiHits)
        ) %>%
        dplyr::arrange(dplyr::desc(max_sample_count)) %>%
        dplyr::ungroup() %>%
        dplyr::slice(1:topGenesCount)
    
    # matrix
    mat <- maf_data %>%
        dplyr::select(-Hugo_Symbol, -max_sample_count) %>%
        as.matrix()
    rownames(mat) <- maf_data$Hugo_Symbol
    return(mat)
}

plotMutProfile <- function(maf,
                           class = "SP",
                           title = "Mutational profile",
                           topGenesCount = 10,
                           driverGenesFile = NULL) {
        
        class.options = c('SP', 'CS', 'SPCS')
        if(!class %in% class.options){
            stop("class can only be either 'SP', 'CS' or 'SPCS'")
        }

    # data frame
    maf_data <- classifyMut(maf, class, driverGenesFile)
    # View(mat)
   
    # matrix 
    mat <- genHeatmapPlotMatrix(maf_data, topGenesCount = topGenesCount)
    # View(mat)

    
    multi_hit_exist = FALSE
    for (i in 1:nrow(mat)) {
        for (j in 1:ncol(mat)) {
            if (length(temp <- grep("Multi_hits", mat[i, j]))) {
                multi_hit_exist = TRUE
                break
            }
        }
    }
        
    col_type <- function(class) {
        if (class == "SP") {
            cols <- c("#3C5488FF", "#00A087FF", "#F39B7fFF")
            names(cols) <- c("Shared","P_shared", "Private")
        } else if (class == "CS") {
            cols <- c("#00A087FF", "#3C5488FF")
            names(cols) <- c("Clonal", "Subclonal")
        } else if (class == "SPCS") {
            cols <-
                c(
                    "#00A087FF",
                    "#3C5488FF",
                    "#8491B4FF",
                    "#F39B7FFF", 
                    "#E64B35FF",                    
                    "#4DBBD5FF"                    
                )
            names(cols) <-
                c(
                    "Shared_Clonal",
                    "Shared_Subclonal",
                    "P_shared_Clonal",
                    "P_shared_Subclonal",
                    "Private_Clonal",
                    "Private_Subclonal"                    
                )
        }
        
        return(cols)
    }

    alter_fun <- function(class){
        if(class == "SP"){
            l <- list(
            background = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = "#CCCCCC", col = NA)),
            Private = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SP")["Private"], col = NA)),
            Shared = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SP")["Shared"], col = NA)),
            P_shared = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SP")["P_shared"], col = NA)),
            Multi_hits = function(x, y, w, h)
                grid::grid.points(x, y, pch = 16, size = grid::unit(0.5, "char")
            ))
        }else if(class == "CS"){
            l <- list(
            background = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = "#CCCCCC", col = NA)),
            Clonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("CS")["Clonal"], col = NA)),
            Subclonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("CS")["Subclonal"], col = NA)),
            Multi_hits = function(x, y, w, h)
                grid::grid.points(x, y, pch = 16, size = grid::unit(0.5, "char") 
                ))
        }else if(class == "SPCS" ){
            l <- list(
            background = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = "#CCCCCC", col = NA)),
            Private_Clonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["Private_Clonal"], col = NA)),
            Private_Subclonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["Private_Subclonal"], col = NA)),
            Shared_Clonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["Shared_Clonal"], col = NA)),
            Shared_Subclonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["Shared_Subclonal"], col = NA)),
            P_shared_Clonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["P_shared_Clonal"], col = NA)),
            P_shared_Subclonal = function(x, y, w, h)
                grid::grid.rect(x, y, w * 0.9, h * 0.9,
                                gp = grid::gpar(fill = col_type("SPCS")["P_shared_Subclonal"], col = NA)),
            Multi_hits = function(x, y, w, h)
                grid::grid.points(x, y, pch = 16, size = grid::unit(0.5, "char") 
            ))
        }
        return(l)            
    }

    heatmap_legend <- function(class, title = NULL) {
        param <- list(
            title = title,
            at = names(col_type(class)),
            labels = sub("_", "-", names(col_type(class)))
        )
        return(param)
    }        

    ht <- suppressMessages(
        ComplexHeatmap::oncoPrint(
            mat,
            alter_fun = alter_fun(class),
            col = col_type(class),
            column_title = title,
            heatmap_legend_param = heatmap_legend(class, title),
            remove_empty_columns = TRUE,
            remove_empty_rows = TRUE,
            pct_digits = 2,
            pct_side = "right",
            row_names_side = "left",
            show_column_names = TRUE
        )
    )

    if (multi_hit_exist) {
        ComplexHeatmap::draw(ht,
                             heatmap_legend_list = list(
                                 ComplexHeatmap::Legend(
                                     labels = "Multi_hits",
                                     type = "points",
                                     pch = 16
                                 )
                             ))
    } else {
        ComplexHeatmap::draw(ht)
    }
    
    maf_data %>% dplyr::select(-unique_sample_count)
    return(maf_data)
}