#' testNeutral
#' @description Evaluat whether a tumor follows neutral evolution or under strong selection
#' during the growth based on variant frequency distribution (VAF) of subclonal 
#' The subclonal mutant allele frequencies of a follow a simple power-law distribution predicted by neutral growth.  
#' 
#' @references Williams MJ, Werner B, Barnes CP, Graham TA, Sottoriva A. Identification of neutral tumor evolution across cancer types. 
#' Nat Genet. 2016;48(3):238–244. doi:10.1038/ng.3489
#' 
#' @param maf the Maf object generated by readMaf
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @param min.depth the minimun depth of coverage. Defalut: 10
#' @param R2.threshold the threshod of R2 to decide whether a tumor follows neutral evolution. Default: 0.98
#' @param min.VAF_adj the minimum value of adjusted VAF value. Default: 0.1
#' @param max.VAF_adj the maximum value of adjusted VAF value. Default: 0.3
#' @param plot logical, whether to print model fitting plot of each sample. Default: TRUE
#' 
#' @examples
#' testNeutral(maf)
#' @export testNeutral

testPowerLaw <- function(
    df, 
    min.VAF_adj, 
    max.VAF_adj, 
    min.depth,
    R2.threshold,
    plot){

	subPowerLaw <- function(
    sample.df,
    min.VAF_adj,
    max.VAF_adj,
    min.depth,
    R2.threshold,
    plot){

		sample.id <- unique(sample.df$Tumor_Sample_Barcode)
    	sample.df <- sample.df %>%
    		dplyr::filter(
    			Status == "Subclonal" & 
    			Ref_allele_depth + Alt_allele_depth > min.depth &
          VAF_adj > min.VAF_adj &
          VAF_adj < max.VAF_adj &
    			!is.na(VAF_adj)
    		)  

		if(nrow(sample.df) < 30){
			R2.out = NA
      vaf.plot  = NA
			warning(paste0("Sample ", sample.id, ": There is no enough eligible mutations can be used."))
		}else{
			max.vaf <- max(sample.df$VAF_adj)
			min.vaf <- min(sample.df$VAF_adj)
			breaks = ceiling((max.vaf - min.vaf)/0.005)
			vafCount =  hist(1/sample.df$VAF_adj, breaks = breaks, plot = F)
			vafCumsum <- data.frame(vafCount$breaks, c(0,cumsum(vafCount$counts)))
			lmModel <- lm(vafCumsum[, 2] ~ vafCumsum[, 1])
      		lmLine = summary(lmModel)
      		x.min <- min(vafCumsum[, 1])
      		x.max <- max(vafCumsum[, 1])
      		y.min <- min(vafCumsum[, 2])
      		y.max <- max(vafCumsum[, 2],
      		             (x.max*lmModel$coefficients[2]+lmModel$coefficients[1]))
      R2 = lmLine$adj.r.squared
      R2.out <- data.frame(
        Tumor_Sample_Barcode = sample.id,
        Eligible_Mut_Count = nrow(sample.df ),
        R2 = R2, 
        Type = dplyr::if_else(
          R2 >= R2.threshold,
          "neutral",
          "non-neutral")
        )
 
      vaf.plot <- NA 
      if(plot){

        R2label <- as.character(paste0(sample.id,':  italic(R)^2 == ', R2))

      	vaf.plot <- ggplot(data = vafCumsum, mapping = aes(x = vafCount.breaks, y = c.0..cumsum.vafCount.counts..)) +
      		      geom_point()+
      		      geom_smooth(method=lm, color="red")+
      		      theme(panel.grid =element_blank(),
      		            panel.border = element_blank(),
      		            panel.background = element_blank(),
      		            axis.line = element_blank(),
      		            axis.ticks = element_line(size = 1),
      		            axis.title = element_text(size = 13,face = "bold",colour = "black"),
      		            axis.text = element_text(size = 10,face = "bold",colour = "black"),
      		            axis.ticks.length = unit(.25, "cm"))+
      		    geom_segment(aes(x = x.min,xend= x.max, y=-Inf,yend=-Inf), size = 1)+
      		    geom_segment(aes(y = y.min ,yend = y.max,x=-Inf,xend=-Inf), size = 1.5)+
      		    scale_x_continuous(breaks = seq(x.min,x.max,(x.max-x.min)/2),
      		                        labels = c(paste0('1/', round(1/x.min,2)),
      		                                  paste0('1/', round(1/(x.min+(x.max-x.min)/2),2)),
      		                                  paste0('1/', round(1/x.max,2))))+
      		    scale_y_continuous(breaks = seq(y.min,y.max,(y.max-y.min)/4),
      		                        labels = round(seq(y.min,y.max,(y.max-y.min)/4)))+
      		                        # labels = c(round(y.min),
      		                        #            round(y.min+(y.max-y.min)/4),
      		                        #            round(y.min+(y.max-y.min)*2/4),
      		                        #            round(y.max)))+
      		    xlab("Inverse allelic frequency 1/vaf")+
      		    ylab("Cumulative number of SSNVs")+
      		    annotate("text",
      		              x = quantile(vafCumsum[, 1])[2],
      		              y = max(vafCumsum[, 2]),
      		              label = R2label,
      		              size = 4,
                        fontface = "bold",
                        parse = TRUE)

      		}
	      
		}
	
		return(list(model.fitting.out = R2.out, model.fitting.plot = vaf.plot))		
	}

	patient.R2 <- df %>%
		dplyr::group_by(Tumor_Sample_Barcode) %>%
		dplyr::group_map(~subPowerLaw(.,
          min.VAF_adj,
          max.VAF_adj,
          min.depth,
          R2.threshold,
          plot), 
          keep = TRUE) %>%
    rlang::set_names(unique(df$Tumor_Sample_Barcode))
	
  #neutralTest.out <- data.frame(
	    #Tumor_Sample_Barcods = unique(df$Tumor_Sample_Barcode), 
	    #R2 = patient.R2) %>%
	    #dplyr::mutate(Type = dplyr::if_else(
	        #R2 >= R2.threshold,
	        #"neutral",
	        #"non-neutral"))

  return(patient.R2)       
   #return(list(data.frame = neutralTest.out, plot.list = patient.plot))    	
}


testNeutral <- function(maf, patient.id = NULL, 
    min.depth = 10, R2.threshold = 0.98,
    min.VAF_adj = 0.1, max.VAF_adj = 0.3, 
    plot = TRUE){
	
	mafData <- maf@data

    if(! "CCF" %in% colnames(mafData)){
        stop(paste0("Error: inferring whether a tumor follows neutral evolution requires CCF data.",
            "No CCF data was found when generate Maf object."))
    }

    if(is.null(patient.id)){
        patient.id = unique(mafData$Patient_ID)
    }else{
        patient.setdiff <- setdiff(patient.id, unique(mafData$Patient_ID))
        if(length(patient.setdiff) > 0){
            stop(paste0("Patient ", patient.setdiff, " can not be found in your data"))
        }
    }

    R2.list <- mafData %>%
    	dplyr::group_by(Patient_ID) %>%
    	dplyr::group_map(~testPowerLaw(.,
        min.VAF_adj, 
        max.VAF_adj, 
        min.depth, 
        R2.threshold, 
        plot), 
        keep = TRUE) %>%
    	rlang::set_names(patient.id)    	

    return(R2.list)
}
