#' @title treeGO
#' @description Perform GO enrichment analysis of trunk/branch mutations of a phylogenetic tree.
#' @param phyloTree a phyloTree object generated by getPhyloTree function
#' @param driverGenesFile The file with driver gene list. Default NULL.
#' @param GO.type one of "BP", "MF", and "CC" sub-ontologies, or "ALL" for pooling 3 GO sub-ontologies. Default type="ALL"
#' @param pval cutoff value of pvalue. Default pval=0.05
#' @param qval cutoff value of qvalue. Default qval=0.2
#' @param pAdjustMethod one of "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". Default pAdjustMethod="BH"
#' @param plotType one of "dot", "bar"
#' @param showCategory category numbers
#' 
#' 
#' @examples 
#' treeGO(phyloTree, GO.type = "BP")
#' @return GO enrichment results
#' @import clusterProfiler pdp
#' @export treeGO

treeGO <- function(phyloTree, driverGenesFile = NULL, GO.type="BP", pval=0.05, pAdjustMethod="BH", 
                      qval=0.2, plotType="dot", showCategory=5){
  

  GO.options = c('MF', 'BP', 'CC', "ALL")
    if(!GO.type %in% GO.options){
        stop("GO.type can only be either 'MF', 'BP' 'CC' or 'ALL'")
    }
  
  if(!is.null(driverGenesFile)){
      ## read putative driver genes' list
      driverGenes <- as.character(read.table(
          driverGenesFile, header = FALSE, quote="", sep="\n", stringsAsFactors = FALSE)[,1])
  }

  branches <- phyloTree@mut.branches
  patientID <- phyloTree@patientID
    
  GO.branch.result <- data.frame()
  all.genes <- c()
  egoPlot.list <- list()
  egoResult.list <- list() 
  plot.branchNames <- c()
  result.branchNames <- c()

  x <- 1
  y <- 1 
  for (i in 1:length(branches)){
    branch <- branches[[i]]
    branchID <- names(branches)[i]
    ## split the gene symbol by ","
    geneSymbol <- unique(unlist(strsplit(as.character(branch$Hugo_Symbol), split = ",")))
    if(!is.null(driverGenesFile)&!is.null(driverGenes)){
        geneSymbol <- geneSymbol[geneSymbol %in% driverGenes]
    }
    all.genes <- unique(c(all.genes, geneSymbol))
    
    message(paste("Processing branch: ", branchID, sep = ""))
    ego.branch <- GO_analysis(geneSymbol, GO.type, pval, pAdjustMethod,
                qval, patientID, branchID)
    
    if(!is.null(ego.branch)){
      egoResult.list[[x]] <- ego.branch@result
      result.branchNames <- c(result.branchNames, branchID)
      x <- x+1
      if(min(ego.branch@result$p.adjust) > pval | min(ego.branch@result$qvalue, na.rm=T) > qval){
        message(paste("0 enriched term found for branch ", branchID, sep = ""))
      }
      else{      
        plot.branchNames <- c(plot.branchNames, branchID)
        if (plotType == "dot"){
          go.plot <- dotplot(ego.branch, showCategory=showCategory) + ggtitle(branchID)
        }else if (plotType == "bar"){
          go.plot <- barplot(ego.branch, showCategory=showCategory) + ggtitle(branchID)
        }
        egoPlot.list[[y]] <- go.plot
        y <- y+1
      }
    }
  }

  ego.all <- GO_analysis(unique(all.genes), GO.type, pval, pAdjustMethod,
   qval, patientID, name="All")
  ego.all.result <- ego.all@result
  egoResult.list[[x]] <- ego.all.result
  result.branchNames <- c(result.branchNames, "All")
  if(min(ego.all.result$p.adjust) > pval | min(ego.all.result$qvalue, na.rm = T) > qval){
      message(paste("0 enriched terms found in ", patientID, sep = ""))
    }else{
    plot.branchNames <- c(plot.branchNames, "All")
    if (plotType == "dot"){
      go.plot <- dotplot(ego.all, showCategory=showCategory) + ggtitle(ego.all.result$Case)
    }else if (plotType == "bar"){
      go.plot <- barplot(ego.all, showCategory=showCategory)+ ggtitle(ego.all.result$Case)
    }
    egoPlot.list[[y]] <- go.plot  
  }

  names(egoResult.list) <- result.branchNames
  names(egoPlot.list) <- plot.branchNames
  ego <- list(egoResult.list, egoPlot.list)
  names(ego) <- c("GO.category", "GO.plot")

  return(ego)
}


GO_analysis <- function(genes=NULL, GO.type=GO.type, pval=pval, pAdjustMethod=pAdjustMethod,
                        qval=qval, patientID=patientID, name=name){
    GO.type <- toupper(GO.type)
    GO.type <- match.arg(GO.type, c("BP", "MF", "CC", "ALL"))
    
    ego <- enrichGO(gene          = genes,
                    OrgDb         = org.Hs.eg.db,
                    keyType       = 'SYMBOL',
                    ont           = GO.type,
                    pvalueCutoff  = pval,
                    pAdjustMethod = pAdjustMethod,
                    qvalueCutoff  = qval
    )
    
    if (!is.null(ego) && nrow(ego@result) > 0){
        if(name == "All"){
            ego@result$Case <- patientID
        }else{
            ego@result$branch <- name
        }
    }
    return(ego)
}

