#' @title treePathway
#' @description Perform pathway enrichment analysis of trunk/branch mutations of a phylogenetic tree.
#' 
#' 
#' @param phyloTree a phyloTree object generated by getPhyloTree function.
#' @param geneList list of genes to restrict the analysis. Default NULL.
#' @param pathway.type one of "KEGG" or "Reactome". Default type="KEGG"
#' @param pval cutoff value of pvalue. Default pval=0.05
#' @param pAdjustMethod one of "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none". 
#' Default is "BH"
#' @param qval cutoff value of qvalue. Default qval=0.2
#' @param plotType one of "dot", "bar", default is "dot"
#' @param showCategory number of categories will be shown, default is 5
#' @param patient.id select the specific patients. Default: NULL, all patients are included

#' @examples
#' treePathway(phyloTree, pathway.type = "KEGG")
#' @return pathway enrichment results

#Pathway analysis
treePathway <- function(phyloTree, geneList = NULL, pathway.type="KEGG", pval=0.05, pAdjustMethod="BH",
                           qval=0.2,  plotType="dot", showCategory =  5, patient.id = NULL, withinType = FALSE){
    
  if(!is.null(patient.id)){
        patient.setdiff <- setdiff(patient.id, names(phyloTree))
        if(length(patient.setdiff) > 0){
            stop(paste0(patient.setdiff, " can not be found in your data"))
        }
        phyloTree <- phyloTree[names(phyloTree)  %in% patient.id] 
  }

  pathway.options = c('KEGG', 'Reactome')
    if(!pathway.type %in% pathway.options){
        stop("pathway.type can only be either 'KEGG' or 'Reactome'")
    }
  selectedGenes <- NULL
  if(!is.null(geneList)){
      selectedGenes <- geneList
  }
  
  result.list <- suppressWarnings(lapply(phyloTree,doTreePathway,
                        selectedGenes = selectedGenes,
                        pathway.type= pathway.type,
                        pval= pval,
                        pAdjustMethod= pAdjustMethod,
                        qval= qval,
                        plotType= plotType,
                        showCategory =  showCategory,
                        withinType = withinType)) 
  return(result.list)

}