#'  treeMutSig
#' @description Figure out the intersection of the variants on different branches 
#' in phyloTree object and output the treeMSOutput for further summary and plot functions.
#' 
#' 
#' @param phyloTree a phyloTree object generated by phyloTree function.
#' @param geneList list of genes to restrict the analysis. Default NULL.
#' @param min.mut.count the threshold for the variants in a branch. Default 15.
#' @param signaturesRef The parameter used for deconstructSig. Default "cosmic_v2". Option: "genome_cosmic_v3","exome_cosmic_v3","nature2013".
#' @param patient.id select the specific patients. Default: NULL, all patients are included
#' @return a list of data frames, each one contains treeMSOutput, containing information about each set/branch's mutational signature.
#' 
#' @importFrom pracma lsqnonneg
#' @importFrom Biostrings getSeq
#' @examples
#' treeMutSig(phyloTree, geneList=NULL, min.mut.count=15, signaturesRef="cosmic")
#' treeMutSig(phyloTree, plot = T)
#' @export  treeMutSig


## Mutational Signature function
treeMutSig <- function(phyloTree,
                       geneList=NULL,
                       min.mut.count=15,
                       signaturesRef="cosmic_v2",
                       withinType = FALSE,
                       patient.id = NULL,
                       use.shiny = FALSE){
    
    signaturesRef.options <- c("cosmic_v2","nature2013","genome_cosmic_v3","exome_cosmic_v3")
    if(!signaturesRef %in% signaturesRef.options){
        stop("signaturesRef can only be either 'cosmic_v2','nature2013','genome_cosmic_v3' or 'exome_cosmic_v3'")
    } 
    
    if(!is.null(patient.id)){
        patient.setdiff <- setdiff(patient.id, names(phyloTree))
        if(length(patient.setdiff) > 0){
            stop(paste0(patient.setdiff, " can not be found in your data"))
        }
        phyloTree <- phyloTree[names(phyloTree)  %in% patient.id] 
    }
    treeMSOutput <- lapply(phyloTree, doTreeMutSig,
                           geneList = geneList,
                           min.mut.count = min.mut.count,
                           signaturesRef = signaturesRef,
                           tri.counts.method = tri.counts.method,
                           withinType = withinType,
                           use.shiny = use.shiny)
    mutSigSummary <- lapply(treeMSOutput, doMutSigSummary, withinType)
    cos_sim.mat <- lapply(treeMSOutput,function(x)x$cos_sim.mat)
    sig.spectrum <- lapply(treeMSOutput,function(x)x$sig.spectrum)
    
    return(list(mutSig.summary = mutSigSummary, cos_sim.mat = cos_sim.mat, mutSig.spectrum = sig.spectrum))
}