#'  triMatrix 
#' @description Calculate the frequency of 96 trinucleotide mutation based on somatic SNVs. 
#' 
#' @param phyloTree phyloTree or phyloTreeList object generated by \code{\link{getPhyloTree}} function.
#' @param patient.id Select the specific patients. Default: NULL, all patients are included
#' @param withinTumor Exploring signatures within tumor. Default: FALSE.
#' @return The frequency of 96 trinucleotide mutation.
#' 
#' @importFrom Biostrings getSeq
#' @importFrom S4Vectors Rle
#' @examples
#' maf.File <- system.file("extdata/", "HCC_LDC.maf", package = "MesKit")
#' clin.File <- system.file("extdata/", "HCC_LDC.clin.txt", package = "MesKit")
#' ccf.File <- system.file("extdata/", "HCC_LDC.ccf.tsv", package = "MesKit")
#' maf <- readMaf(mafFile=maf.File, ccfFile = ccf.File, refBuild="hg19")
#' 
#' ## Load a reference genome.
#' library(BSgenome.Hsapiens.UCSC.hg19)
#' 
#' phyloTree <- getPhyloTree(maf, patient.id = 'HCC8257')
#' triMatrix(phyloTree)
#' @export  triMatrix


triMatrix <- function(phyloTree,
                      patient.id = NULL,
                      withinTumor = FALSE){
  ## check input data
  phyloTree_list <- checkPhyloTreeInput(phyloTree, patient.id = patient.id)
  
  result <- subTriMatrix(phyloTree_list, withinTumor = withinTumor)
  if(length(result) == 0){
    return(NA)
  }else{
    return(result)
  }
  
}