#' tumorClonesPlot
#' @description Visualize the CCF distribution of subclones and mutations((loci.tsv and cluster.tsv generated by PyClone are required).
#
#' @param maf an Maf object generated by readMaf function.
#' @param clone.min.mut specify the minimum mutation number of a subclone.
#' @param clone.min.aveCCF specify the minimum average CCF value of a subclone.
#' @return CCF distribution of subclones and mutations in the form of radar plot and dot plot, respectively.
#'
#' @examples
#' tumorClonesPlot(maf)
#' importFrom ggridges scale_discrete_manual
#' @export tumorClonesPlot

tumorClonesPlot <- function(maf, clone.min.mut=5, clone.min.aveCCF=0.1){
  ccfCluster <- maf@ccf.cluster
  if(is.null(ccfCluster)){
    stop("ccf data of cluster was not found when readMaf")
  }
  ccfCluster <- ccfCluster[which(ccfCluster$size>=5 & ccfCluster$mean>=0.1),c(1,2,4)]
  cluster.ids <- unique(ccfCluster$cluster_id)

  mean <- max(ccfCluster$mean)
  label <- factor(ccfCluster$sample_id)
  ccfLoci <- maf@ccf.loci
  if(is.null(ccfCluster)){
    stop("ccf data of loci was not found when readMaf")
  }
  ccfLoci <- ccfLoci[which(!is.na(ccfLoci$variant_allele_frequency)),]
  loci <- ccfLoci[which(ccfLoci$cluster_id %in% cluster.ids),]
  
  radar_plot <- ggplot(ccfCluster, aes(x=sample_id, y=mean, fill=factor(cluster_id))) + geom_bar(stat="identity") + coord_polar()+ 
          theme_bw() + ggsci::scale_fill_npg(labels=as.character(seq(length(cluster.ids)))) + 
            geom_text(y = 2*mean, label = label,position = position_identity())+
            theme(panel.grid = element_blank(),
            panel.border= element_blank(),
            axis.text.x = element_blank(), 
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            axis.title = element_blank())+
          labs(fill = "Tumor clone")+
          theme(legend.position = "top")+
          theme(legend.title = element_text(size = 11, face = "bold"))+   
          theme(legend.text = element_text(size = 10, face = "bold"))+ 
          theme(plot.margin = unit(c(0.2, 0.05, 0.2, 0.05), "inches"))

  loci_dotplot <- ggplot(data=loci, aes(x=sample_id, y=cellular_prevalence, color=factor(cluster_id))) + 
          geom_point(size=1.5)+ theme_bw()+ ggsci::scale_color_npg()+
          theme(panel.border = element_blank(),axis.line = element_line(colour = "black"))+
          theme(panel.grid = element_blank(),
          panel.border= element_blank(),
          axis.text.x = element_text(size = 10, angle = 45, vjust = 1,hjust = 1, face = "bold"), 
          axis.text.y = element_text(size = 10, hjust = 1, face = "bold"),
          axis.ticks = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 11, face = "bold"))+
          labs(y = "Cellular prevalence")+
          theme(legend.position = "none")
  title <- ggdraw() + draw_label("Clonal frequency of tumor clones and the corresponding mutation", fontface = "bold")
  # radar_dotplot <- grid.arrange(radar_plot, loci_dotplot, ncol = 2)
  p <- ggdraw(xlim = c(0,1.05))+draw_plot(radar_plot, x = 0, y = 0, width = 0.5) + draw_plot(loci_dotplot, x = 0.55, y = 0, width = 0.5)
  radar_dotplot <- plot_grid(title, p, ncol = 1, rel_heights=c(0.09, 1))
  return(radar_dotplot)
}




