#' vafCluster
#' @description Generate variant allele frequency(VAF) frequency distribution
#'  curve in different mode.
#'  
#' @param maf A Maf object generated by readMaf function.
#' @param patient.id Select the specific patients in Maf list. Default: NULL, all patients are included.
#' @param chrSilent Select chromosomes needed to be dismissed. Default NULL.
#' @param mutType select Proper variant classification you need. Default "All". Option: "nonSyn".
#' @param use.indel Logical value. Whether to use INDELs besides somatic SNVs. Default: TRUE.
#' @param segCN.file the segment file.
#' @param min.vaf The minimum value of VAF. Default: 0. Option: on the scale of 0 to 1
#' @param max.vaf The maximum value of VAF. Default: 0. Option: on the scale of 0 to 1
#' @param showMATH logical. Whether to show MATH Scores in the plot. Default TRUE 
#' @param plotOption character. Three options for displaying clustering of VAFs in samples. Default "compare"
#' "compare": prints comparison of VAFs distribution among samples;
#' "combine" prints VAFs distribution of samples all together;
#' @param use.adjVAF Cluster by adjusted VAF. Default: FALSE. 
#' @examples
#' vafCluster(maf, plotOption="compare")
#' vafCluster(maf, plotOption="combine", showMATH=FALSE)
#' 
#'
#' @export vafCluster

## Main function for VAF plot
vafCluster <-function(maf,
                      segCN.file = NULL,
                      patient.id = NULL,
                      chrSilent = NULL,
                      mutType = "All",
                      use.indel = TRUE,
                      min.vaf = 0.02,
                      max.vaf = 1,
                      showMATH = TRUE, 
                      plotOption = "combine",
                      use.adjVAF = FALSE){
  plotOption <- match.arg(plotOption, choices = c('combine', 'compare'), several.ok = FALSE)
  
  if(class(maf) == "classMaf"){
      maf_list <- list(maf)
  }else if(class(maf) == "classMaf_list"){
      ## patient filter
      if(!is.null(patient.id)){
          maf_list <- subsetMaf_list(maf, patient.id = patient.id)
      }else{
          maf_list <- maf@patient.list 
      }
      
  }else{
      stop("maf should be either classMaf or classMaf_list")
  }
  
  ## readsegment
  seg <- NULL
  if(!is.null(segCN.file)){
    seg <- readSegment(segCN.file = segCN.file)
  }
  
  result.list <- lapply(maf_list, doVafCluster,
                        seg = seg,
                        chrSilent = chrSilent,
                        mutType = mutType,
                        use.indel = use.indel,
                        min.vaf = min.vaf,
                        max.vaf = max.vaf,
                        showMATH = showMATH, 
                        plotOption = plotOption,
                        use.adjVAF = use.adjVAF)
  if(length(result.list ) > 1){
      return(result.list )
  }else if(length(result.list) == 0){
      return(NA)
  }else{
      return(result.list [[1]])
  }
  return(result.list)
}