#' vafCluster
#' @description Generate variant allele frequency (VAF) frequency distribution curve.
#'  
#' @param maf Maf or MafList object generated by \code{\link{readMaf}} function.
#' @param patient.id Select the specific patients. Default: NULL, all patients are included.
#' @param segFile The segment file.
#' @param min.vaf The minimum value of VAF. Default: 0. Option: on the scale of 0 to 1
#' @param max.vaf The maximum value of VAF. Default: 0. Option: on the scale of 0 to 1
#' @param withinTumor Cluster VAF within tumors in each patients,default is FALSE.
#' @param use.tumorLabel Logical (Default: FALSE). Rename the 'Tumor_Sample_Barcode' with 'Tumor_Label'.
#' @param ... Other options passed to \code{\link{subMaf}}
#' 
#' @examples
#' maf.File <- system.file("extdata/", "HCC_LDC.maf", package = "MesKit")
#' clin.File <- system.file("extdata/", "HCC_LDC.clin.txt", package = "MesKit")
#' ccf.File <- system.file("extdata/", "HCC_LDC.ccf.tsv", package = "MesKit")
#' maf <- readMaf(mafFile=maf.File, clinicalFile = clin.File, ccfFile=ccf.File, refBuild="hg19")
#' vafCluster(maf, patient.id = 'HCC8257')
#' 
#' @import ggridges mclust
#' @importFrom grDevices boxplot.stats
#' @return clustering plots of vaf
#' @export vafCluster

## Main function for VAF plot
vafCluster <-function(maf,
                      patient.id = NULL,
                      segFile = NULL,
                      min.vaf = 0.02,
                      max.vaf = 1,
                      withinTumor = FALSE,
                      use.tumorLabel = FALSE,
                      ...){
  # plotOption <- match.arg(plotOption, choices = c('combine', 'compare'), several.ok = FALSE)
  ## check input data
  maf_list <- checkMafInput(maf, patient.id = patient.id)
  
  processVafcluster_maf <- function(m){
    ## remove mutation in CNA regions
    if(!is.null(segFile)){
      seg <- readSegment(segFile = segFile)
      m <- copyNumberFilter(m,seg)
    }
    
    maf_data <- subMaf(m, min.vaf = min.vaf, max.vaf = max.vaf, ...)
    patient <- getMafPatient(m)
    
    
    
    if(nrow(maf_data) == 0){
      message("Warning :there was no mutation in ", patient, " after filtering.")
      return(NA)
    }
    
    if(use.tumorLabel){
      if(!"Tumor_Label" %in% colnames(maf_data)){
        stop("There is no information about the Tumor_Label.Please check clinical data in readMaf or let use.tumorLabel be FALSE")
      }
      maf_data <- maf_data %>% 
        dplyr::mutate(Tumor_Sample_Barcode = .data$Tumor_Label)
    }
    
    ## extract vaf info
    if(withinTumor){
      maf_data$VAF <- maf_data$Tumor_Average_VAF
      maf_data$ID <- maf_data$Tumor_ID
      id_list <- unique(maf_data$ID)
    }else{
      maf_data$ID <- maf_data$Tumor_Sample_Barcode
      id_list <- unique(maf_data$ID)
    }
    
    sample_result <- lapply(id_list, processVafcluster_sample, maf_data, patient)
    na_idx <- which(!is.na(sample_result))
    sample_result <- sample_result[na_idx]
    
    plot_list <- lapply(sample_result, function(x)x$p)
    names(plot_list) <- id_list[na_idx]
    
    rebuild_data_list <- lapply(sample_result, function(x)x$subdata)
    
    rebuild_data <- dplyr::bind_rows(rebuild_data_list)
    
    return(list(cluster.data = rebuild_data, cluster.plot = plot_list))
    
  }
  
  processVafcluster_sample <- function(id, maf_data, patient){
    subdata <- maf_data[maf_data$ID == id]
    ## data cleaning
    if (nrow(subdata) < 3) {
      message(paste0("Error: mutations of Sample ", id, " are not enough for clustering"))
      return(NA)
    }
    
    ## infer possible cluster from maf_data
    message(paste("Processing ", id," of ", patient, sep = ""))
    cluster_result <- mclust::densityMclust(subdata$VAF, G=seq_len(7), verbose=FALSE)
    subdata$cluster <- as.character(cluster_result$classification)
    
    ## define outfilter
    out_vaf <- boxplot.stats(subdata$VAF)$out
    subdata[subdata$VAF %in% out_vaf]$cluster <- "outlier"
    
    p  <- drawVAFCombine(subdata)
    
    return(list(p = p, subdata = subdata))
  }
  
  result <- lapply(maf_list, processVafcluster_maf)
  result <- result[!is.na(result)]
  
  if(length(result) > 1){
      return(result)
  }else if(length(result) == 0){
      return(NA)
  }else{
      return(result[[1]])
  }
  
}



